import { defineLesson, type SubjectCurriculum } from "../learning-types";

export const englishCurriculum: SubjectCurriculum = {
  id: "english",
  title: "英语",
  tagline: "从一句问候开始，让单词帮助我们理解和交流。",
  description: "从日常听认、字母与词，到短句、对话和简短阅读的首批 12 课；先理解意思，再尝试使用。",
  stages: [
    { id: "english-listen-stage", title: "听见日常英语", subtitle: "让一句话与一个情境联系起来。" },
    { id: "english-word-stage", title: "认识字母与词", subtitle: "看见字母，认出身边物品的名称。" },
    { id: "english-details-stage", title: "说颜色和数量", subtitle: "给物品增加一点具体信息。" },
    { id: "english-sentence-stage", title: "连成简单句", subtitle: "介绍物品，表达自己的喜好。" },
    { id: "english-dialogue-stage", title: "你一句，我一句", subtitle: "问得清楚，也礼貌地回应。" },
    { id: "english-reading-stage", title: "读懂并介绍", subtitle: "从短文找依据，用学过的话表达。" },
  ],
  domains: [
    { id: "english-listening", title: "听认与回应", description: "理解日常用语，联系场景作出回应。", color: "#ba7855" },
    { id: "english-vocabulary", title: "字母与词汇", description: "把字母形式、完整单词与意思联系起来。", color: "#5476b5" },
    { id: "english-communication", title: "句子与交流", description: "用简单句介绍、问答和请求。", color: "#4f8e7b" },
    { id: "english-reading", title: "阅读与表达", description: "从短文找信息，再组织自己的介绍。", color: "#9c78ad" },
  ],
  sources: [
    { title: "教育部：义务教育课程方案和课程标准（2022 年版，含英语课程标准）", url: "https://hudong.moe.gov.cn/srcsite/A26/s8001/202204/t20220420_619921.html" },
    { title: "British Council TeachingEnglish：Alphabet，字母名与大小写的学习", url: "https://www.teachingenglish.org.uk/teaching-resources/teaching-primary/lesson-plans/level-1/alphabet" },
  ],
  lessons: [
    defineLesson({
      id: "english-greetings", title: "见面与告别，先说一句", domainId: "english-listening", stageId: "english-listen-stage", prerequisites: [],
      goal: "把 Hello 和 Goodbye 与见面、告别的情境联系起来。",
      why: "先知道一句英语在什么时候有用，再认识里面的声音和词，后面就能参加简单对话。",
      story: { title: "在门口遇见朋友", text: "早上，Ben 看见朋友，说“Hello!”。放学分开时，他说“Goodbye!”。同样是对朋友说话，情境不同，用语也不同。" },
      activity: { kind: "listen", instruction: "先看情境和意思，设备支持时可点选听完整短语。也可以只看文字或请家人示范；这里不录音、不判断发音。", lang: "en-GB", items: [
        { text: "Hello!", meaning: "你好！见面时可以这样问候。" },
        { text: "Hi!", meaning: "嗨！另一种常见的简短问候。" },
        { text: "Goodbye!", meaning: "再见！告别时可以这样说。" },
      ] },
      explanation: ["Hello 和 Hi 常用于见面打招呼，可以把它们与见到朋友的画面联系起来。", "Goodbye 常用于分开时告别，不要把问候与告别的意思混在一起。", "学习时先理解什么时候使用，再尝试跟着完整短语说；是否能播放声音取决于设备。"],
      takeaway: "一句话先连上情境，英语才有了要表达的意思。",
      checks: [
        { prompt: "刚见到朋友，哪句话适合打招呼？", options: ["Goodbye!", "Three.", "Hello!"], answer: 2, explanation: "Hello 用来问候，适合刚见到朋友时使用。" },
        { prompt: "你和朋友准备各自回家，可以说什么？", options: ["A book.", "Goodbye!", "Red."], answer: 1, explanation: "准备分开时可以用 Goodbye 表达再见。" },
      ],
    }),
    defineLesson({
      id: "english-instructions", title: "听懂一句简单的指令", domainId: "english-listening", stageId: "english-listen-stage", prerequisites: ["english-greetings"],
      goal: "把 Sit down、Stand up、Open your book 与具体动作配对。",
      why: "问候让我们参与交流，听懂动作要求能帮助我们跟上课堂，并在以后提出请求。",
      story: { title: "小课堂开始了", text: "老师说“Stand up.”，大家站起来；再说“Sit down.”，大家坐下。动作帮助我们理解整句话，不用先逐字翻译。" },
      activity: { kind: "pairs", instruction: "读短语并看情境，把每一句与合适的动作配起来；可以请家人读给你听。", pairs: [
        { left: "Stand up.", right: "站起来", explanation: "把 Stand up 作为一个整体，与站起的动作联系起来。" },
        { left: "Sit down.", right: "坐下", explanation: "Sit down 表达坐下，与站起来的动作不同。" },
        { left: "Open your book.", right: "打开你的书", explanation: "这句要求打开书，不是合上书或离开座位。" },
      ] },
      explanation: ["先把完整短语与动作联系起来，Stand up 是站起来，Sit down 是坐下。", "听指令要留意整句话，不能只听到一个熟悉的词就猜动作。", "没听清时可以请对方再说一次；理解以后再行动，不必靠猜测。"],
      takeaway: "把一句英语和具体动作连接起来，听懂后再回应。",
      checks: [
        { prompt: "Sit down. 对应哪个动作？", options: ["坐下", "站起来", "打开书"], answer: 0, explanation: "Sit down 表达坐下，Stand up 才是站起来。" },
        { prompt: "朋友说“Open your book.”，你可以怎样回应这个要求？", options: ["把书合上", "跑到门外", "打开自己的书"], answer: 2, explanation: "Open your book 表示打开你的书，动作应与完整短语的意思一致。" },
      ],
    }),
    defineLesson({
      id: "english-letters", title: "字母有名字，也有大小写", domainId: "english-vocabulary", stageId: "english-word-stage", prerequisites: ["english-instructions"],
      goal: "认出几组大小写字母，知道字母名称不等于它在所有单词里的发音。",
      why: "已经听过完整短语，再看写下来的形式，就能发现词由字母组成；认识字母帮助辨认单词，但不能替代听完整词。",
      story: { title: "大小写伙伴", text: "字母 A 和 a 是一对大小写伙伴，B 和 b 也是。单词 cat 由 c、a、t 组成；把三个字母的名称念一遍，并不等于读出了 cat 这个词。" },
      activity: { kind: "pairs", instruction: "找出同一个字母的大小写伙伴。这里练习认形，不把单个字母的电脑朗读当作音素示范。", pairs: [
        { left: "A", right: "a", explanation: "A 是大写形式，a 是对应的小写形式。" },
        { left: "B", right: "b", explanation: "B 与 b 是同一个字母的两种书写形式。" },
        { left: "C", right: "c", explanation: "C 与 c 都是字母 C，大小写形式不同。" },
      ] },
      explanation: ["英语词语用字母写下来，一个字母通常有大写和小写形式。", "字母有名称，但名称不一定等于它在某个单词中的声音，不能把逐个念字母名当成读单词。", "学习单词时同时看完整写法、听完整读音、联系意思；例如 cat 指猫，而不只是三个字母的清单。"],
      takeaway: "大小写帮助认字母，读单词还要联系完整声音和意思。",
      checks: [
        { prompt: "B 的小写伙伴是哪一个？", options: ["d", "a", "b"], answer: 2, explanation: "B 对应的小写形式是 b，d 和 a 是其他字母。" },
        { prompt: "看到 cat，只把 c、a、t 的字母名称逐个念出，算读出了这个词吗？", options: ["不算，还要学习完整词的读音和意思", "一定算，字母名就是词音", "只要念得快就算"], answer: 0, explanation: "逐个说字母名称是在拼写字母，读单词还需要把字母与这个词的实际声音和意思联系起来。" },
      ],
    }),
    defineLesson({
      id: "english-objects", title: "身边物品也有英语名字", domainId: "english-vocabulary", stageId: "english-word-stage", prerequisites: ["english-letters"],
      goal: "把 book、bag、pen 与书、书包和笔联系起来。",
      why: "知道词由字母组成后，先从身边物品认识词；这些词以后会成为介绍和请求里的内容。",
      story: { title: "整理书包", text: "Ben 整理学习用品：book 是书，bag 是包，pen 是笔。先看物品，再看单词，就能把名字和实际东西连起来。" },
      activity: { kind: "listen", instruction: "对照物品意思认读完整单词，可选听读；请把注意力放在词与物品的联系上。", lang: "en-GB", items: [
        { text: "book", meaning: "书，可以打开来阅读。" },
        { text: "bag", meaning: "包；在这个故事中指装学习用品的书包。" },
        { text: "pen", meaning: "笔；这里用来指钢笔、圆珠笔等笔类。" },
      ] },
      explanation: ["看见 book，可以联系一本书；看见 bag，可以联系一个包。", "book 和 bag 都以 b 开头，但不是同一个词，要看完整写法并联系意思。", "词语放进情境后会更容易记住；学习时可以指着身边物品说对应的名称。"],
      takeaway: "看完整单词，把它与真正的物品联系起来。",
      checks: [
        { prompt: "book 对应什么物品？", options: ["书包", "书", "球"], answer: 1, explanation: "book 表示书，bag 才表示包。" },
        { prompt: "book 和 bag 都以 b 开头，所以它们意思一样吗？", options: ["不一样，要看完整单词", "一样，只看第一个字母就够", "只在蓝色书包里一样"], answer: 0, explanation: "词的完整形式和意思都要关注，同一个开头不能说明两个词相同。" },
      ],
    }),
    defineLesson({
      id: "english-colours", title: "用颜色词补充一个细节", domainId: "english-vocabulary", stageId: "english-details-stage", prerequisites: ["english-objects"],
      goal: "理解 red、blue、yellow，并区分物品名称和颜色信息。",
      why: "知道物品叫什么以后，可以加上颜色让描述更具体；后面就能回答关于颜色的问题。",
      story: { title: "哪一个书包", text: "桌旁有两个书包。Ben 说“a red bag”，是在说一个红色的包。“bag”告诉我们是什么，“red”告诉我们什么颜色。" },
      activity: { kind: "pairs", instruction: "把颜色词与对应的中文意思配起来，再想想它能给哪个物品补充信息。", pairs: [
        { left: "red", right: "红色的", explanation: "red 可以描述红色，如 a red bag。" },
        { left: "blue", right: "蓝色的", explanation: "blue 可以描述蓝色，如 a blue pen。" },
        { left: "yellow", right: "黄色的", explanation: "yellow 可以描述黄色，如 a yellow book。" },
      ] },
      explanation: ["red、blue、yellow 分别表达红色、蓝色和黄色。", "在 a red bag 里，red 是颜色信息，bag 是物品名称，这两部分回答不同的问题。", "本课这些短语把颜色词放在物品词前，如 a blue pen 表示一支蓝色的笔。"],
      takeaway: "物品词告诉我们是什么，颜色词让描述更具体。",
      checks: [
        { prompt: "a blue pen 中，哪个词告诉我们颜色？", options: ["pen", "a", "blue"], answer: 2, explanation: "blue 表示蓝色，pen 表示笔。" },
        { prompt: "想说一个红色的包，哪个短语合适？", options: ["a yellow pen", "a blue bag", "a red bag"], answer: 2, explanation: "red 表示红色，bag 表示包，两者组合与要介绍的物品相符。" },
      ],
    }),
    defineLesson({
      id: "english-numbers", title: "用数量词说有几个", domainId: "english-vocabulary", stageId: "english-details-stage", prerequisites: ["english-objects", "english-colours"],
      goal: "理解 one、two、three，并观察本课物品词在多个时加 s 的变化。",
      why: "颜色让描述具体，数量则说明有几个；把数量和物品连起来，就能介绍自己有什么。",
      story: { title: "两支笔，不是一支", text: "Ben 有两支笔，可以说“two pens”，也可以说“I have two pens.”，意思是“我有两支笔”。one 是一，two 是二，three 是三。" },
      activity: { kind: "pairs", instruction: "把数量短语与意思配起来，留意 one pen 和 two pens 的小变化。", pairs: [
        { left: "one pen", right: "一支笔", explanation: "one 表示 1，这里一支笔写作 pen。" },
        { left: "two pens", right: "两支笔", explanation: "two 表示 2，本课 pen 表示多个时加 s。" },
        { left: "three books", right: "三本书", explanation: "three 表示 3，本课 book 表示多个时加 s。" },
      ] },
      explanation: ["one、two、three 告诉我们数量，后面的物品词告诉我们在数什么。", "本课的 pen、book 表示多个时加 s：two pens、three books；不是所有英语词都只需加 s。", "I have two pens. 是完整的介绍，表示我有两支笔，可以换成已学过的其他数量和物品。"],
      takeaway: "说数量时，让数词和所数的物品一起出现。",
      checks: [
        { prompt: "three books 表示多少本书？", options: ["两本", "一本", "三本"], answer: 2, explanation: "three 表示 3，books 表示多本书。" },
        { prompt: "想介绍“我有两支笔”，哪句话合适？", options: ["I have two pens.", "I have three books.", "I have one pen."], answer: 0, explanation: "two 是两，pens 是笔，整句表达我有两支笔。" },
      ],
    }),
    defineLesson({
      id: "english-introduce", title: "This is…介绍眼前物品", domainId: "english-communication", stageId: "english-sentence-stage", prerequisites: ["english-colours", "english-numbers"],
      goal: "把 This is 与 a red bag 等内容连成介绍一句话。",
      why: "已经认识物品和细节，可以把词放进简单句；完整的介绍能帮助别人知道你正在说什么。",
      story: { title: "介绍自己的学习用品", text: "Ben 指着一个红色的包说：“This is a red bag.”，意思是“这是一个红色的包。”这句话把物品和颜色都说清了。" },
      activity: { kind: "sequence", instruction: "按“这是—一个红色的包—句末标点”的意思，排好这句介绍。", items: [
        { id: "object", text: "a red bag" }, { id: "stop", text: "." }, { id: "start", text: "This is" },
      ], order: ["start", "object", "stop"], success: "This is a red bag. 一句完整的介绍把“这是”和“是什么”连在了一起。" },
      explanation: ["This is 在这里表示“这是”，后面补上正在介绍的东西。", "a red bag 表示一个红色的包，red 给 bag 补充颜色。", "把句首字母大写、句末加上句号，是本课陈述句的书写方式；意思清楚与书写清楚都重要。"],
      takeaway: "先用 This is 引出眼前物品，再补上它是什么。",
      checks: [
        { prompt: "This is a red bag. 在介绍什么？", options: ["一个红色的包", "一支蓝色的笔", "三本书"], answer: 0, explanation: "a red bag 表示一个红色的包。" },
        { prompt: "眼前是一支蓝色的笔，用哪句介绍合适？", options: ["This is a red bag.", "This is a yellow book.", "This is a blue pen."], answer: 2, explanation: "blue pen 表示蓝色的笔，与眼前物品相符。" },
      ],
    }),
    defineLesson({
      id: "english-like", title: "I like…表达我喜欢什么", domainId: "english-communication", stageId: "english-sentence-stage", prerequisites: ["english-introduce"],
      goal: "理解 I like…表达喜好，并与介绍物品的 This is…区分。",
      why: "能介绍眼前物品以后，还能表达自己的感受和喜好；不同句子是在完成不同的交流任务。",
      story: { title: "说说自己喜欢的颜色", text: "Ben 指着红色的包说“This is a red bag.”。接着他说“I like blue.”，意思是他喜欢蓝色；包的颜色和他的喜好不一定相同。" },
      activity: { kind: "sort", instruction: "看句子正在做什么，把物品介绍与表达喜好分开。", categories: ["介绍眼前物品", "表达自己的喜好"], items: [
        { text: "This is a red bag.", category: 0, explanation: "This is 在这里介绍一个红色的包。" },
        { text: "I like blue.", category: 1, explanation: "I like 表达我喜欢，blue 是喜欢的颜色。" },
        { text: "I like books.", category: 1, explanation: "这句表达我喜欢书，books 在这里指书这一类。" },
      ], success: "先看说话目的：是在介绍眼前的东西，还是在表达我喜欢什么。" },
      explanation: ["I like 在这里表示“我喜欢”，后面接喜欢的内容，如 blue 或 books。", "This is a red bag. 说明眼前是什么；I like blue. 说明自己的喜好，两句并不矛盾。", "表达喜好时要尊重真实想法，别人喜欢的颜色可以与你不同。"],
      takeaway: "介绍物品和表达喜好，是两种不同的意思。",
      checks: [
        { prompt: "I like blue. 表达什么意思？", options: ["我有三本书", "这个包一定是蓝色", "我喜欢蓝色"], answer: 2, explanation: "I like 表示我喜欢，blue 表示蓝色。" },
        { prompt: "Lily 喜欢红色，哪句适合让她表达自己的喜好？", options: ["I like red.", "This is a pen.", "I like blue."], answer: 0, explanation: "Lily 自己说话时用 I，red 表示红色，所以 I like red. 与她的想法相符。" },
      ],
    }),
    defineLesson({
      id: "english-dialogue", title: "先听问题，再回答对应信息", domainId: "english-communication", stageId: "english-dialogue-stage", prerequisites: ["english-like", "english-colours", "english-greetings"],
      goal: "理解 What colour is it?，并用 It is…回应颜色问题。",
      why: "会介绍和表达以后，可以与别人一问一答；回答要对准问题，不能只是念一句自己会说的话。",
      story: { title: "猜书包的颜色", text: "朋友指着一个蓝色的包问：“What colour is it?”，意思是“它是什么颜色？”Ben 回答：“It is blue.”，意思是“它是蓝色的。”" },
      activity: { kind: "sequence", instruction: "按见面、提问、回答的顺序，把这段关于蓝色书包的对话排好。", items: [
        { id: "answer", text: "Ben: It is blue." }, { id: "hello", text: "Lily: Hello, Ben!" }, { id: "question", text: "Lily: What colour is it?" },
      ], order: ["hello", "question", "answer"], success: "问的是颜色，回答也提供颜色信息。对话前后才能接上。" },
      explanation: ["What colour is it? 在问它是什么颜色，不是在问数量或个人喜好。", "回答 It is blue. 时，it 指双方正在看的那个物品。", "先明白对方问什么，再给出对应信息；I like blue. 表达喜好，不能总拿来代替物品颜色的回答。"],
      takeaway: "对话要前后相接：问什么，就先回答那件事。",
      checks: [
        { prompt: "What colour is it? 主要在问什么？", options: ["你叫什么名字", "物品的颜色", "有几个物品"], answer: 1, explanation: "colour 表示颜色，这个问句是在询问物品颜色。" },
        { prompt: "朋友指着红色的包问 What colour is it?，哪句回答直接对应问题？", options: ["I like blue.", "It is red.", "I have two pens."], answer: 1, explanation: "问的是眼前物品的颜色，所以回答 It is red.；另两句表达喜好或拥有的数量。" },
      ],
    }),
    defineLesson({
      id: "english-please", title: "提出请求，也接住对方的回应", domainId: "english-listening", stageId: "english-dialogue-stage", prerequisites: ["english-dialogue", "english-instructions", "english-objects"],
      goal: "把 Can I have…please?、Here you are.、Thank you. 放进一个礼貌交流情境。",
      why: "会按问题回应后，再把需求和礼貌连起来；熟悉的物品词就能用于真实生活交流。",
      story: { title: "请朋友递一支笔", text: "Ben 需要一支笔，问“Can I have a pen, please?”。Lily 递给他时说“Here you are.”，Ben 回答“Thank you.”。" },
      activity: { kind: "pairs", instruction: "把这三句话与它们在对话里的作用配起来。", pairs: [
        { left: "Can I have a pen, please?", right: "礼貌地请求一支笔", explanation: "这句在表达需求，please 让请求更礼貌。" },
        { left: "Here you are.", right: "把东西递给对方时说“给你”", explanation: "在递笔的情境里，这句配合把物品交给对方。" },
        { left: "Thank you.", right: "收到帮助后表达感谢", explanation: "Thank you 表达谢谢，让对方知道你感谢他的帮助。" },
      ] },
      explanation: ["Can I have a pen, please? 是请求，不代表对方必须答应。", "Here you are. 在递东西的场景里表示“给你”，要联系动作来理解。", "得到帮助后可以说 Thank you.；礼貌交流也包括等待和尊重对方的回应。"],
      takeaway: "先说清需要什么，再礼貌等待、回应和感谢。",
      checks: [
        { prompt: "想礼貌地请求一支笔，哪句合适？", options: ["It is blue.", "Can I have a pen, please?", "Goodbye!"], answer: 1, explanation: "这句话明确请求一支笔，并用 please 表达礼貌。" },
        { prompt: "朋友把笔递给你并说 Here you are.，你可以怎样回应？", options: ["What colour is it? 一定不能先感谢", "必须让他再给一支", "Thank you."], answer: 2, explanation: "收到帮助时可以说 Thank you 表达感谢，不需要再提出额外要求。" },
      ],
    }),
    defineLesson({
      id: "english-read", title: "从三句话里找到确切信息", domainId: "english-reading", stageId: "english-reading-stage", prerequisites: ["english-numbers", "english-dialogue", "english-please"],
      goal: "读懂由熟悉词句组成的短文，从原文找到物品、颜色和数量。",
      why: "日常词句已经能理解，把它们放在一起就能读短文；有根据地找信息，为自己的介绍做准备。",
      story: { title: "Ben 的学习用品", text: "读这三句：“This is my bag. It is blue. I have two pens.” my 表示“我的”；Ben 在介绍自己的包和笔。" },
      activity: { kind: "evidence", instruction: "阅读短文，选出有原文依据的信息；别把自己的猜想加进去。", passage: "This is my bag. It is blue. I have two pens.", clues: [
        { text: "Ben 的包是蓝色的。", correct: true, explanation: "第一句介绍 bag，第二句 It is blue. 继续说明这个包的颜色。" },
        { text: "Ben 有两支笔。", correct: true, explanation: "I have two pens. 直接说明有两支笔。" },
        { text: "Ben 的两支笔都是红色的。", correct: false, explanation: "短文说明了笔的数量，没有说明笔的颜色。" },
      ], conclusion: "能确定包是蓝色、有两支笔；不能把包的颜色或自己的猜想搬到笔上。" },
      explanation: ["先认出熟悉的词和句子，不需要把每个词孤零零地背一遍。", "It is blue. 的 it 接着前面的 bag，所以蓝色说的是包。", "找答案时回到原句；文字没有说明的笔的颜色，应说这里还不知道。"],
      takeaway: "把句子前后连起来，再用原文支持答案。",
      checks: [
        { prompt: "根据短文，Ben 有几支笔？", options: ["两支", "一支", "三支"], answer: 0, explanation: "I have two pens. 中的 two 说明数量是两支。" },
        { prompt: "另一篇短文只写 I have three books.，能确定书的颜色吗？", options: ["能，一定蓝色", "能，一定红色", "不能，句子只说明数量和物品"], answer: 2, explanation: "three books 表示三本书，句中没有颜色信息，不能自行补成事实。" },
      ],
    }),
    defineLesson({
      id: "english-share", title: "用学过的话完成一个小介绍", domainId: "english-reading", stageId: "english-reading-stage", prerequisites: ["english-read", "english-like", "english-introduce"],
      goal: "根据物品和喜好的线索，组织两三句与事实相符的简单介绍。",
      why: "读懂别人的介绍后，可以把熟悉句子重新组合，用英语表达自己要说的内容。",
      story: { title: "Lily 的介绍卡", text: "Lily 的资料是：一个红色的包、两支笔、喜欢蓝色。介绍时，每一句都要与对应资料相符，不能因为她喜欢蓝色就把包说成蓝色。" },
      activity: { kind: "evidence", instruction: "看资料，为 Lily 选择符合意思的介绍句。这里不要求三句话只能按一种顺序说。", passage: "Lily：包是红色；有两支笔；喜欢蓝色。", clues: [
        { text: "This is a red bag.", correct: true, explanation: "这句介绍一个红色的包，与资料相符。" },
        { text: "I have two pens.", correct: true, explanation: "这句由 Lily 自己说，表达她有两支笔。" },
        { text: "I like blue.", correct: true, explanation: "这句表达 Lily 喜欢蓝色，与物品实际是什么颜色可以不同。" },
        { text: "This is a blue bag.", correct: false, explanation: "资料里的包是红色，喜欢蓝色并不说明包也是蓝色。" },
      ], conclusion: "每句话都有对应的信息，物品、数量和喜好说清楚，就组成了有内容的小介绍。" },
      explanation: ["先想要介绍什么，再挑选已学过的句子；句子是帮助表达的工具。", "This is…、I have…、I like…分别介绍物品、拥有的东西和喜好，不要混用意思。", "可以请家人听一听是否明白；这里的小题检查内容理解，不自动评定口语、发音或写作水平。"],
      takeaway: "让每一句英语都对应你真正想传递的一条信息。",
      checks: [
        { prompt: "Lily 的包是红色，她喜欢蓝色。哪两句可以同时正确？", options: ["This is a red bag. / I like blue.", "I have three books. / It is yellow.", "This is a blue bag. / I like red."], answer: 0, explanation: "物品颜色和个人喜好是不同信息，红色的包与喜欢蓝色可以同时成立。" },
        { prompt: "你实际有三本书，想用学过的句子介绍，哪句与信息相符？", options: ["This is a red bag.", "I have three books.", "I have two pens."], answer: 1, explanation: "I have…用于介绍拥有的东西，three books 与三本书的实际信息相符。" },
      ],
    }),
  ],
};
