import { defineLesson, type SubjectCurriculum } from "../learning-types";

export const geographyCurriculum: SubjectCurriculum = {
  id: "geography",
  title: "地理",
  tagline: "从身边的位置，慢慢认识整个世界",
  description: "先认位置、方向和地图，再观察地形、水与天气，最后理解地球上的海陆和人与环境的联系。",
  stages: [
    { id: "geography-position", title: "从身边找位置", subtitle: "先说相对位置，再约定方向。" },
    { id: "geography-map", title: "读懂一张小地图", subtitle: "看图例，找起点，说明路线。" },
    { id: "geography-land", title: "地面与水怎样相连", subtitle: "认识起伏，跟着河水观察。" },
    { id: "geography-weather", title: "今天与长久的天气", subtitle: "从每天记录，走向多年规律。" },
    { id: "geography-earth", title: "把眼光放到地球", subtitle: "从模型认识地球和海陆。" },
    { id: "geography-people", title: "人与环境一起看", subtitle: "利用所学解释选择和影响。" },
  ],
  domains: [
    { id: "geography-space", title: "位置与地图", description: "说清在哪里、怎样到达。", color: "#5476c8" },
    { id: "geography-nature", title: "地形与水", description: "观察地面的形态和水的联系。", color: "#35947c" },
    { id: "geography-climate", title: "天气与气候", description: "分清短时变化与长期特征。", color: "#b17a2b" },
    { id: "geography-home", title: "地球与生活", description: "认识共同家园中的联系。", color: "#9570b8" },
  ],
  lessons: [
    defineLesson({
      id: "geography-relative", title: "说位置，先说在谁旁边", stageId: "geography-position", domainId: "geography-space", prerequisites: [],
      goal: "用参照物说明位置，知道换个参照物，位置说法也会变。",
      why: "认识世界从说清“在哪里”开始，别人才能根据你的话找到同一个地方。",
      story: { title: "图书角在哪里", text: "你说“图书角在旁边”，新同学仍然找不到。补上一句“面对黑板时，图书角在教室左边”，方向和参照就清楚多了。" },
      activity: { kind: "pairs", instruction: "把不完整的位置说法，和能补充清楚的信息连起来。", pairs: [{ left: "在左边", right: "面对黑板时，在教室左边", explanation: "说明面对哪里，左右才不容易混淆。" }, { left: "在旁边", right: "在图书馆旁边", explanation: "图书馆是大家都能识别的参照物。" }, { left: "离这里很近", right: "从校门沿小路走到第一个路口", explanation: "说清起点和路线，比只有远近感受更容易寻找。" }] },
      explanation: ["参照物是用来帮助说明位置的地方或物品。", "左和右与面朝的方向有关，转身后左右说法可能改变。", "描述位置时，把参照物和方向一起说明，别人更容易理解。"],
      takeaway: "说清在哪里，要有大家认识的参照。",
      checks: [
        { prompt: "哪句话最能帮助新同学找到图书角？", options: ["面对黑板，在教室左边", "就在那边", "很漂亮的地方"], answer: 0, explanation: "这句话说明了观察方向和相对位置。" },
        { prompt: "你转身以后，说某棵树在左边还是右边可能改变，为什么？", options: ["树一定移动了", "地面消失了", "你的朝向改变了"], answer: 2, explanation: "相对左右与人的朝向有关，不一定是树发生移动。" },
      ],
    }),
    defineLesson({
      id: "geography-directions", title: "用东南西北约定方向", stageId: "geography-position", domainId: "geography-space", prerequisites: ["geography-relative"],
      goal: "在明确北向的示意图上辨认东南西北。",
      why: "左右会随人的朝向改变，约定东南西北能让不同的人更容易说同一个方向。",
      story: { title: "操场北边的图书馆", text: "校园示意图的北向朝上，操场在中间，图书馆在它上方。我们可以说，图书馆在操场北边。这是这张图的约定，读别的图还要看方向标记。" },
      activity: { kind: "map", instruction: "本图北朝上、东在右；只表示位置，不按真实距离缩小。从操场向北走一格，到图书馆。", cells: ["花园", "图书馆", "教室", "小路", "操场", "食堂", "校门", "小路", "树荫"], start: 4, target: 1, success: "到了操场北边的图书馆。图上向上表示北，是因为这张图明确约定了北朝上。" },
      explanation: ["在这张北朝上的图中，上北、下南、左西、右东。", "面对北时，右手边是东；转身以后，东仍在原来的地理方向。", "有的地图会旋转摆放，读图先找方向标记，不能永远把纸的上方当作北。"],
      takeaway: "先认清图的北向，再判断其他方向。",
      checks: [
        { prompt: "在北朝上的图中，右边表示哪个方向？", options: ["西", "东", "南"], answer: 1, explanation: "本图采用北朝上的约定，所以右边是东。" },
        { prompt: "一张地图的北向箭头指向纸的右侧，哪里才是北？", options: ["箭头指向的右侧", "仍然一定是纸的上方", "哪里都一样"], answer: 0, explanation: "要依据方向标记读图，不能只记纸面位置。" },
      ],
    }),
    defineLesson({
      id: "geography-legend", title: "图上的小符号是什么意思", stageId: "geography-map", domainId: "geography-space", prerequisites: ["geography-directions"],
      goal: "用图例读懂符号，并理解示意图与实际物体的区别。",
      why: "知道方向以后，还要知道图上的符号代表什么，才能真正读懂地图。",
      story: { title: "公园地图上的小树", text: "公园地图用一个小树符号表示树林，用蓝色曲线表示小河。小树符号并不是只说那里恰好有一棵树，具体含义要查看这张图的图例。" },
      activity: { kind: "pairs", instruction: "按本课给出的图例配对。这些是学习用的约定，不代表所有地图都一样。", pairs: [{ left: "本图的树形符号", right: "树林", explanation: "图例约定一个符号可以代表一片树林。" }, { left: "本图的蓝色曲线", right: "小河", explanation: "线状符号可以表示延伸的河流。" }, { left: "本图标有“学”的方框", right: "学校", explanation: "符号和文字一起帮助辨认地点。" }] },
      explanation: ["图例说明符号、颜色和线条在这张图里代表什么。", "地图会挑选信息，不能把每片叶子、每块砖都画出来。", "图上的符号大小不一定就是物体实际大小；比较真实距离还要看比例说明。"],
      takeaway: "读地图先看图例，不把小符号当成真实物体的全部。",
      checks: [
        { prompt: "地图上一棵小树形符号代表什么，最应该先看哪里？", options: ["纸张的背面颜色", "自己的猜想", "这张地图的图例"], answer: 2, explanation: "图例告诉我们作者怎样约定符号的含义。" },
        { prompt: "两张图上的学校方框一样大，能断定两所学校真实面积一样吗？", options: ["不能，符号大小不一定按真实面积画", "能，方框一样就说明实际一样", "只要都是彩色图就能"], answer: 0, explanation: "符号服务于表达，真实大小需要比例和实际资料来判断。" },
      ],
    }),
    defineLesson({
      id: "geography-route", title: "从起点走到目标，把路线说清", stageId: "geography-map", domainId: "geography-space", prerequisites: ["geography-relative", "geography-legend"],
      goal: "把位置、方向和经过的地点连成一段路线。",
      why: "认出地图上的地方后，就可以用它规划怎样到达，并检查自己有没有走对。",
      story: { title: "去公园里的展馆", text: "你在公园西南边的入口，目标是东北边的展馆。可以先走向北，再向东；也可能有别的路线。说明路线时，要从同一个起点开始。" },
      activity: { kind: "map", instruction: "本图北朝上、右为东，不按真实距离缩小。每次走上下左右一格，从入口出发，到展馆；这里可以有不止一种路线。", cells: ["路口", "小路", "展馆", "小路", "花坛旁", "小路", "入口", "小路", "路口"], start: 6, target: 2, success: "你把起点、经过的位置和目标连起来了。能到达目标的路线可能不止一条。" },
      explanation: ["先找起点，再找目标，避免把别人的起点当作自己的起点。", "一步一步说方向，也可以用经过的地点检查路线。", "示意图上的格数是本次练习的步数，不是实际公里数或步行时间。"],
      takeaway: "一条清楚的路线，要说明从哪里出发、怎样走、到哪里。",
      checks: [
        { prompt: "描述去展馆的路线，第一步应先说明什么？", options: ["展馆墙面颜色", "自己最喜欢的花", "从哪个起点出发"], answer: 2, explanation: "相同目标从不同起点出发，走法可能不同。" },
        { prompt: "两条路线都能到达目标，只看这张不按比例的图，能准确算出各走几分钟吗？", options: ["能，一格一定一分钟", "能，颜色深的路更快", "不能，还需要实际距离和行走情况"], answer: 2, explanation: "位置示意图没有提供足够的真实距离和速度信息。" },
      ],
    }),
    defineLesson({
      id: "geography-landforms", title: "地面有高低，也有起伏", stageId: "geography-land", domainId: "geography-nature", prerequisites: ["geography-legend", "geography-route"],
      goal: "根据整体起伏特征，初步区分山地和平原。",
      why: "地图能说明位置，观察地形还能帮助理解路为什么绕行、水为什么流向某处。",
      story: { title: "窗外两种风景", text: "一段旅程中，窗外是连绵山岭；另一段是较平坦开阔的田野。我们先观察大片地面的高低与起伏，不能只看一块小石头。" },
      activity: { kind: "sort", instruction: "根据整片地面的描述分类，而不是根据有没有一棵树。", categories: ["山地的典型特征", "平原的典型特征"], items: [{ text: "山岭相连，地面起伏明显", category: 0, explanation: "起伏明显、山岭较多是山地的典型特点。" }, { text: "较低平，大片地面较平坦", category: 1, explanation: "平原通常地势较低、地面较平坦。" }, { text: "道路常要沿山势绕行", category: 0, explanation: "山岭和坡地会影响路线选择。" }, { text: "较平坦开阔的地面便于连续展开田地", category: 1, explanation: "这是平原地区可能提供的条件，不表示每块平原都种田。" }], success: "地形判断看整体高低与起伏，地形也会影响道路和土地利用。" },
      explanation: ["地形说的是地表的形态，例如山地、平原等。", "山地起伏明显；平原较低平、较开阔，但实际地面并非完全像桌面一样平。", "世界上还有高原、丘陵、盆地等多种地形，本课先学会观察，再逐步扩展。"],
      takeaway: "认识地形，先看大片地面的高低和起伏。",
      checks: [
        { prompt: "判断一片地方是不是山地，哪种观察更有帮助？", options: ["只数一棵树有几片叶子", "看整体是否山岭多、起伏明显", "看一辆车的颜色"], answer: 1, explanation: "地形关注的是地表整体形态，而不是单个物品。" },
        { prompt: "在山岭之间修路，为什么可能需要绕行？", options: ["需要考虑坡度、山岭等实际条件", "所有路都必须画成弯线", "因为地图纸太小"], answer: 0, explanation: "路线受到真实地形条件影响，不能只画一条直线。" },
      ],
    }),
    defineLesson({
      id: "geography-river", title: "顺着水流，连接上游和下游", stageId: "geography-land", domainId: "geography-nature", prerequisites: ["geography-landforms"],
      goal: "理解地表水通常沿地势向低处流，并用流向区分上游与下游。",
      why: "看懂高低起伏以后，就能跟着水流理解不同地方怎样相连。",
      story: { title: "小溪的旅行", text: "在这个例子里，山坡上的雨水汇成小溪，小溪再流入较大的河，最后到海湾。不是每条河都直接入海，有些会流入湖泊等地方。" },
      activity: { kind: "sequence", instruction: "按故事里这条水流的先后经过排列，不把它当作所有河流的唯一路线。", items: [{ id: "bay", text: "海湾" }, { id: "creek", text: "小溪" }, { id: "slope", text: "山坡上汇集的雨水" }, { id: "river", text: "较大的河流" }], order: ["slope", "creek", "river", "bay"], success: "这一例子中，水沿地势汇集，经过小溪和河流进入海湾，把沿途的地方联系起来。" },
      explanation: ["地表水在重力作用下，通常顺着地势向较低处流。", "顺水流的方向是往下游，逆着水流的方向是往上游。", "上游、下游不是固定的北和南，也不是永远对应地图的上方和下方。"],
      takeaway: "认上游与下游，要看水流方向，不能只看纸的上下。",
      checks: [
        { prompt: "判断一段河流的下游方向，应该主要看什么？", options: ["河水向哪里流", "地图哪边颜色更深", "河流名字有几个字"], answer: 0, explanation: "顺着水流向前是往下游，与纸面上下不是一回事。" },
        { prompt: "河水在图上从右往左流，图左侧这一段相对在什么方向？", options: ["下游方向", "一定是北方", "一定是上游"], answer: 0, explanation: "既然水往左流，沿水流到左侧就是往下游。" },
      ],
    }),
    defineLesson({
      id: "geography-weather", title: "记录今天的天空和冷暖", stageId: "geography-weather", domainId: "geography-climate", prerequisites: ["geography-relative", "geography-river"],
      goal: "用时间、地点和观察项目，描述一次天气情况。",
      why: "同一个地方也会随时间变化，连续记录可以帮助我们发现变化，而不只凭感觉。",
      story: { title: "班级天气记录员", text: "你写下“今天很冷”，同学还想知道是哪里、几点。补上“校园，上午九点，气温、云量和是否下雨”，记录就更容易比较。" },
      activity: { kind: "sort", instruction: "把记录分成天气观察和其他信息。", categories: ["天气观察", "其他信息"], items: [{ text: "今天上午校园气温 18℃", category: 0, explanation: "时间、地点和气温共同描述了这次冷暖情况。" }, { text: "下午下起小雨", category: 0, explanation: "降雨是天气现象。" }, { text: "午后天空的云变多了", category: 0, explanation: "云的变化也是天气观察的一部分。" }, { text: "图书馆新买了三本书", category: 1, explanation: "这是校园事情，没有描述天气。" }], success: "天气可以从冷暖、云、降雨和风等方面观察，记录时要说明时间和地点。" },
      explanation: ["天气描述某个地方较短时间内的大气情况。", "气温、降水、风和云等都能帮助我们描述天气，不只有晴或雨。", "比较记录时，尽量采用相同地点、相近时间和一致方法，变化才容易看清。"],
      takeaway: "一次清楚的天气记录，要写地点、时间和观察结果。",
      checks: [
        { prompt: "哪条天气记录最清楚？", options: ["校园，上午九点，阴天，18℃", "外面不一样", "今天的书包很好看"], answer: 0, explanation: "它包含地点、时间和具体天气信息。" },
        { prompt: "上午晴朗，下午下雨，说明什么？", options: ["至少有一条记录一定是假的", "天气可以在较短时间内变化", "天气一天内绝不会改变"], answer: 1, explanation: "天气并非整天固定，记录不同时间的变化正是观察的意义。" },
      ],
    }),
    defineLesson({
      id: "geography-climate", title: "看很多年的记录，才谈气候", stageId: "geography-weather", domainId: "geography-climate", prerequisites: ["geography-weather"],
      goal: "分清一天的天气与一个地区长期的气候特征。",
      why: "把许多天气记录放在一起，才能研究长期特点；一次冷暖不能代表全部规律。",
      story: { title: "一次下雪能说明什么", text: "某地今天下雪，这是一次天气现象。要知道那里冬季通常怎样，需要看许多年的温度、降水等记录，不能只用这一天作结论。" },
      activity: { kind: "sort", instruction: "看看句子说的是短时情况，还是多年通常的特点。", categories: ["天气", "气候特征"], items: [{ text: "今天午后有一场雨", category: 0, explanation: "这是短时间内发生的情况。" }, { text: "这个地区多年的夏季通常炎热", category: 1, explanation: "它描述一个地区长期常见的季节特点。" }, { text: "明天早晨可能有大风", category: 0, explanation: "这是对短期天气的预报。" }, { text: "根据多年记录，这里冬季降水通常较少", category: 1, explanation: "它依据多年资料归纳长期特点。" }], success: "区分天气与气候，一个关键是观察和归纳的时间范围。" },
      explanation: ["天气关心短时间内怎样，气候关心一个地区长期通常怎样。", "研究气候需要长期记录，常用跨越许多年的资料。", "一次异常冷暖不够判断整个气候变化，结论要与数据范围相配。"],
      takeaway: "一天看天气，多年记录帮助认识气候。",
      checks: [
        { prompt: "哪句话是在描述气候特征？", options: ["今天中午突然下雨", "这里多年的冬季通常较寒冷", "明早有雾的可能性较大"], answer: 1, explanation: "多年通常的特点属于气候描述，另外两项是短时天气。" },
        { prompt: "想比较两个地区夏季通常谁更热，用哪组资料更合适？", options: ["各挑一天的最高温", "两地多年同一季节的温度记录", "只看地图上的名字"], answer: 1, explanation: "应比较相应季节的长期资料，避免偶然天气造成误解。" },
      ],
    }),
    defineLesson({
      id: "geography-globe", title: "从脚下的地方，认识地球", stageId: "geography-earth", domainId: "geography-home", prerequisites: ["geography-legend", "geography-climate"],
      goal: "知道地球整体接近球形，理解地球仪和地图是不同模型。",
      why: "身边地图只画一小片地方，把观察范围扩大，才开始认识这些地方共同所在的地球。",
      story: { title: "为什么地球仪是圆的", text: "站在操场上，脚下看起来很平。把范围放大到整个地球，形状却接近球体。地球仪用缩小的球体帮助我们认识整体，平面地图则便于展开查看。" },
      activity: { kind: "pairs", instruction: "把不同表达方式与它适合帮助观察的内容配起来。", pairs: [{ left: "地球仪", right: "认识接近球形的地球整体", explanation: "球形模型有助于观察各部分在整体上的相对位置。" }, { left: "校园平面示意图", right: "找校园内的地点与路线", explanation: "它选取很小的范围，并不描绘整个地球的外形。" }, { left: "地图的图例和说明", right: "判断符号和表达方式", explanation: "模型都需要说明，不能把简化的画法当成真实世界的全部。" }] },
      explanation: ["地球很大，整体接近球形；在很小范围内看起来平，不等于整体是一张平板。", "地球仪也是缩小、简化的模型，并非真实大小。", "把球面放到平面上会带来变形，不能只凭一幅世界地图上的图形大小比较真实面积。"],
      takeaway: "模型帮助看世界，也要知道模型的范围和局限。",
      checks: [
        { prompt: "地球仪为什么做成球形？", options: ["只为了方便当玩具", "因为操场是圆形", "为了表现地球整体接近球形"], answer: 2, explanation: "地球仪的形状是对地球整体形态的简化表达。" },
        { prompt: "世界平面地图上甲地看起来比乙地大，怎样做更稳妥？", options: ["立刻认定实际一定更大", "查真实面积资料和地图说明", "只看哪个颜色更亮"], answer: 1, explanation: "平面表达可能有变形，实际大小需要合适的资料判断。" },
      ],
    }),
    defineLesson({
      id: "geography-ocean-land", title: "海洋与陆地，共同组成家园", stageId: "geography-earth", domainId: "geography-home", prerequisites: ["geography-globe", "geography-river"],
      goal: "知道地球表面海洋占比较大，并分清表面覆盖与内部组成。",
      why: "认识地球整体以后，还要看表面有哪些不同环境，它们怎样与生活相连。",
      story: { title: "太空照片里的蓝色", text: "从太空看地球，能看见大片海洋。海洋覆盖地球表面大约七成，陆地约三成。说的是表面面积，不是说地球里面每一部分都按这个比例装着水。" },
      activity: { kind: "evidence", instruction: "挑出资料真正支持的说法，留意“表面”这个词。", passage: "科学资料显示：海洋覆盖地球表面约 71%，其余约 29% 是陆地。海水、河水和地下水等属于地球水系统的不同部分。", clues: [{ text: "地球表面的海洋面积比陆地面积大", correct: true, explanation: "约七成大于约三成，这是资料直接支持的比较。" }, { text: "地球内部约七成体积都是海水", correct: false, explanation: "资料讨论表面面积，不能变成内部体积的结论。" }, { text: "每个地区都有七成面积是海洋", correct: false, explanation: "整体比例不代表每个局部都具有相同比例。" }], conclusion: "地球整体的表面以海洋为主，局部地区的海陆情况却各不相同。" },
      explanation: ["陆地与海洋分布在地球表面，海洋面积约占七成。", "海陆交界的地方叫海岸，沿海地区与远离海洋的内陆地区条件不同。", "河流可能把陆地上的水送向海洋，说明海陆环境并非互不相关。"],
      takeaway: "看整体的海陆比例，也要分清每个地方的具体情况。",
      checks: [
        { prompt: "“海洋约占地球表面七成”主要是在比较什么？", options: ["地球内部的金属重量", "每家水杯里的水量", "地球表面的覆盖面积"], answer: 2, explanation: "这说的是表面海洋与陆地面积的比例。" },
        { prompt: "某个校园周围没有海，能推翻地球海洋面积更大的说法吗？", options: ["能，一个校园代表全部地球", "能，只有看得见的海才算", "不能，局部情况不等于整体比例"], answer: 2, explanation: "整体和局部是不同观察范围，不能用一个地方替代整个地球。" },
      ],
    }),
    defineLesson({
      id: "geography-choices", title: "选择一个地方，要一起看哪些条件", stageId: "geography-people", domainId: "geography-home", prerequisites: ["geography-route", "geography-landforms", "geography-climate", "geography-ocean-land"],
      goal: "综合位置、地形、水和天气信息，解释一个生活选择。",
      why: "真实问题往往不只用到一种知识，要把已经学过的条件放在一起想。",
      story: { title: "给班级选观察点", text: "班级想长期观察一小块种植园。甲地平坦、方便到达，附近有取水点；乙地坡陡、不方便取水。还要核对日照、土壤和学校安排，不能只凭一个优点就下决定。" },
      activity: { kind: "evidence", instruction: "选出支持优先考察甲地的条件，同时保留还要核查的问题。", passage: "甲地：地面较平、路程方便、附近有可用取水点。乙地：坡陡、取水较远。目前还没有记录两地日照和土壤情况。", clues: [{ text: "甲地较平坦，方便到达", correct: true, explanation: "这些条件支持把甲地作为优先考察的选项。" }, { text: "甲地附近有可用取水点", correct: true, explanation: "照料植物需要水，这是与任务相关的信息。" }, { text: "甲地一定能种好所有植物", correct: false, explanation: "植物需求不同，日照、土壤等信息也尚未核查。" }], conclusion: "甲地值得优先考察，但完整决定还要结合植物需求、土壤、日照和现场安排。" },
      explanation: ["地点选择通常涉及多种条件，例如能否到达、地面是否合适、有没有水。", "条件与任务要对应：适合种植，不一定就适合所有其他用途。", "信息不够时，先说已有依据和待确认的问题，不急着保证结果。"],
      takeaway: "把多种条件与具体用途连起来，才能解释一个地点选择。",
      checks: [
        { prompt: "为什么本例可以优先考察甲地？", options: ["它已有平坦、便于到达和取水等相关条件", "甲这个字排在前面", "它一定适合所有用途"], answer: 0, explanation: "选择应基于与种植观察任务相关的实际条件。" },
        { prompt: "想把同一地方改作操场，能直接照搬种植园的结论吗？", options: ["能，任何用途都相同", "只要取水近就一定可以", "不能，要按操场用途重新核查条件"], answer: 2, explanation: "不同用途有不同需求，方法可以迁移，结论要重新判断。" },
      ],
    }),
    defineLesson({
      id: "geography-connections", title: "上游的小动作，下游也可能感受到", stageId: "geography-people", domainId: "geography-home", prerequisites: ["geography-river", "geography-weather", "geography-choices"],
      goal: "沿着水流解释人的行为可能影响别处，并选择有依据的保护做法。",
      why: "位置、流向和生活选择连起来，就能认识不同地方的人怎样共同使用环境。",
      story: { title: "雨后的校园水沟", text: "校园路边的水会流进水沟，再接入附近水系。落在地面的垃圾可能被雨水带走。看不见它了，不代表它已经消失，也不代表影响只留在原地。" },
      activity: { kind: "sort", instruction: "根据水会流动的联系，判断哪些做法更有助于减少垃圾进入水体。", categories: ["有助于保护水环境", "可能增加水环境负担"], items: [{ text: "把垃圾放进合适的垃圾桶", category: 0, explanation: "妥善收集可减少垃圾被雨水带进水沟的机会。" }, { text: "把包装纸丢进路边水沟", category: 1, explanation: "垃圾可能顺水移动，还可能堵塞水沟。" }, { text: "参加由老师组织的地面垃圾清理", category: 0, explanation: "在合适安排下清理地面垃圾，有助于减少进入水体的垃圾。" }, { text: "把脏东西冲走，就说它不存在了", category: 1, explanation: "位置改变不等于消失，仍可能影响下游。" }], success: "水把地方连接起来，妥善处理垃圾是在照顾身边，也是在照顾与我们相连的地方。" },
      explanation: ["雨水和河流会把不同地点连接起来，物质也可能随着水移动。", "判断影响要沿着真实流向与处理过程追踪，不能只看眼前是否干净。", "保护环境需要个人行动，也需要垃圾收集、排水处理和共同维护等安排。"],
      takeaway: "认识地方之间的联系，才更懂得照顾共同生活的环境。",
      checks: [
        { prompt: "垃圾顺水漂走，看不见了，说明什么？", options: ["垃圾已经自动消失", "位置变了，仍可能影响下游", "一定不会影响其他地方"], answer: 1, explanation: "随着水移动，不代表物质不再存在。" },
        { prompt: "想解释家附近河流的变化，哪种观察更完整？", options: ["只看一次水面颜色就确定所有原因", "结合上下游、天气和周围活动记录", "只按地图上方下方猜流向"], answer: 1, explanation: "多种相关信息一起看，更能支持对地方联系和变化的解释。" },
      ],
    }),
  ],
  sources: [
    { title: "美国地质调查局：地形图符号", url: "https://www.usgs.gov/publications/topographic-map-symbols" },
    { title: "美国地质调查局：河川径流与水循环", url: "https://www.usgs.gov/water-science-school/science/streamflow-and-water-cycle" },
    { title: "美国地质调查局：河流、小溪及其流向", url: "https://www.usgs.gov/water-science-school/science/rivers-streams-and-creeks" },
    { title: "NASA儿童科学：天气与气候有什么不同", url: "https://science.nasa.gov/kids/videos/video-whats-the-difference-between-weather-and-climate/" },
    { title: "NASA：地球事实与海洋覆盖比例", url: "https://science.nasa.gov/earth/facts/" },
  ],
};
