import { defineLesson, type SubjectCurriculum } from "../learning-types";

export const historyCurriculum: SubjectCurriculum = {
  id: "history",
  title: "历史",
  tagline: "从昨天的故事，认识有证据的过去",
  description: "先学会排时间、找线索，再认识古人的生活、技术与交流，最后用证据解释变化。",
  stages: [
    { id: "history-time", title: "时间有先后", subtitle: "从自己的经历，走向更久以前。" },
    { id: "history-evidence", title: "过去留下了什么", subtitle: "分清实物、记录与想象。" },
    { id: "history-settlement", title: "人们怎样生活", subtitle: "从食物和住处认识古代聚落。" },
    { id: "history-technology", title: "办法怎样改变", subtitle: "认识记录与印刷中的巧思。" },
    { id: "history-exchange", title: "不同地方相遇", subtitle: "沿着道路和水路发现交流。" },
    { id: "history-explain", title: "把线索讲明白", subtitle: "比较变化，为自己的说法找证据。" },
  ],
  domains: [
    { id: "history-order", title: "时间与顺序", description: "说清事情发生在什么时候。", color: "#5476c8" },
    { id: "history-sources", title: "史料与证据", description: "根据留下的材料认识过去。", color: "#9570b8" },
    { id: "history-life", title: "生活与技术", description: "理解食物、住处和工具的变化。", color: "#35947c" },
    { id: "history-connections", title: "交流与变化", description: "看见不同人群之间的联系。", color: "#b17a2b" },
  ],
  lessons: [
    defineLesson({
      id: "history-before-after", title: "先发生什么，后发生什么", stageId: "history-time", domainId: "history-order", prerequisites: [],
      goal: "根据时间词和过程，把三件事情按先后排好。",
      why: "历史研究已经发生的事，先排清顺序，才能进一步问事情怎样变化。",
      story: { title: "我的小小成长相册", text: "相册里有刚出生、上幼儿园和进入小学的照片。照片在桌上的位置可以换，事情发生的顺序却不能随意换。" },
      activity: { kind: "sequence", instruction: "从最早发生的事开始，排出成长顺序。", items: [{ id: "school", text: "进入小学" }, { id: "birth", text: "刚出生" }, { id: "kindergarten", text: "上幼儿园" }], order: ["birth", "kindergarten", "school"], success: "出生在前，上幼儿园随后，进入小学更晚。排列依据是发生时间。" },
      explanation: ["过去是已经发生的事，现在是正在经历的时刻。", "先、后、以前、后来这些词，帮助我们说明时间关系。", "排清先后，不等于已经知道原因；先下雨、后放学，不代表下雨造成了放学。"],
      takeaway: "先排清什么时候发生，再追问怎样发生。",
      checks: [
        { prompt: "把成长照片按发生时间排好，应该依据什么？", options: ["照片大小", "衣服颜色", "事情发生的先后"], answer: 2, explanation: "时间顺序看事情何时发生，不看照片外观。" },
        { prompt: "早上浇花，下午花盆被风吹倒。能只凭先后就说是浇花把花盆弄倒的吗？", options: ["能，前面的事都是原因", "能，因为都是同一天", "不能，还要找有关原因的线索"], answer: 2, explanation: "先后顺序只能说明时间关系，解释原因还需要其他证据。" },
      ],
    }),
    defineLesson({
      id: "history-timeline", title: "把久远的事情放上时间线", stageId: "history-time", domainId: "history-order", prerequisites: ["history-before-after"],
      goal: "用时间线表示先后，知道一条简图可以省略许多时期。",
      why: "个人经历只有几年，把时间拉长，就能把不同历史时期放在一起比较。",
      story: { title: "博物馆的三个展厅", text: "我们挑出汉、唐、宋三个时期，沿时间线了解它们的先后。这只是历史中的几段，中间还有其他时期，不是全部历史。" },
      activity: { kind: "sequence", instruction: "只比较这三个时期：汉在唐之前，唐在宋之前。按从早到晚排列。", items: [{ id: "song", text: "宋" }, { id: "han", text: "汉" }, { id: "tang", text: "唐" }], order: ["han", "tang", "song"], success: "所选时期的顺序是汉、唐、宋。简化时间线不表示它们之间没有别的时期。" },
      explanation: ["时间线把较早的事和较晚的事按约定方向排列。", "汉比唐早，唐比宋早；本课先认识顺序，不需要背一长串年份。", "看时间线还要看说明：画得一样远，不一定表示相隔同样久。"],
      takeaway: "时间线帮助看先后，读图还要留意省略和标注。",
      checks: [
        { prompt: "在汉、唐、宋三个时期中，哪个最早？", options: ["汉", "宋", "唐"], answer: 0, explanation: "这三个时期从早到晚依次是汉、唐、宋。" },
        { prompt: "成长图只标了出生和上小学，说明中间什么事也没发生吗？", options: ["说明没有中间经历", "不能，图中只是省略了许多事情", "说明两件事发生在同一天"], answer: 1, explanation: "简图会选择重要节点，没画出来不等于没有发生。" },
      ],
    }),
    defineLesson({
      id: "history-objects", title: "旧物也会留下线索", stageId: "history-evidence", domainId: "history-sources", prerequisites: ["history-timeline"],
      goal: "认识实物、文字记录和后来想象的区别。",
      why: "我们不能直接回到过去，但可以研究留下来的物品和记录。",
      story: { title: "展柜里的碗", text: "一只出土陶碗能让我们观察材料和形状。旁边画着古人吃饭的复原图，帮助想象场景，但复原图本身不是古人留下的照片。" },
      activity: { kind: "sort", instruction: "看看每项材料从哪里来，放入合适的一类。", categories: ["当时留下的材料", "后来制作的表现"], items: [{ text: "经过考古确认的古代陶碗", category: 0, explanation: "陶碗是当时制作并保存下来的实物。" }, { text: "古人写下的书信", category: 0, explanation: "书信是当时留下的文字记录，还需要了解写信人的情况。" }, { text: "今天画的古代生活想象图", category: 1, explanation: "这是后来的人依据资料或想象绘制的表现。" }], success: "材料的来历不同，能回答的问题也不同。复原图可以帮助理解，但需要核对依据。" },
      explanation: ["古人留下的器物、建筑遗迹和文字，可以成为研究过去的材料。", "读材料要问：是谁留下的、在什么时候、从哪里发现？", "一件物品不能回答所有问题；陶碗的大小可观察，使用者每天说什么却看不出来。"],
      takeaway: "先问线索从哪里来，再判断它能说明什么。",
      checks: [
        { prompt: "想研究古代陶碗怎样制作，哪项材料最直接？", options: ["随意画的童话插图", "经过确认的古代陶碗实物", "今天买的新塑料碗"], answer: 1, explanation: "古代陶碗能直接提供材料、制作痕迹和形状等线索。" },
        { prompt: "只看一张旧校门照片，能确认当时每个学生都喜欢什么游戏吗？", options: ["只要照片够大就能", "能，照片能回答所有问题", "不能，还需要其他材料"], answer: 2, explanation: "照片能显示拍到的景物，不能自动说明每个人的想法。" },
      ],
    }),
    defineLesson({
      id: "history-writing", title: "从甲骨上的字，认识记录", stageId: "history-evidence", domainId: "history-sources", prerequisites: ["history-objects"],
      goal: "知道甲骨文是认识商代的文字材料，并分清传说与已发现的证据。",
      why: "实物可以留下使用痕迹，刻写在上面的文字又让我们多了一种了解过去的办法。",
      story: { title: "骨头上的小字", text: "博物馆里，商代的人刻在龟甲、兽骨上的文字被称为甲骨文。它们留下了当时的一些记录。关于造字的传说很有趣，但不能直接当作某个人造出所有汉字的证明。" },
      activity: { kind: "evidence", instruction: "找出能够支持“商代有人使用文字记录”的线索。", passage: "考古发现中有被确认属于商代的刻辞甲骨，表面刻着能够研究和释读的文字。今天也有人讲述古人造字的传说。", clues: [{ text: "经过确认的商代甲骨上刻有文字", correct: true, explanation: "有明确来历的刻辞甲骨，直接支持当时使用文字。" }, { text: "今天流传着一个造字故事", correct: false, explanation: "传说能反映文化想象，但不足以单独证明具体历史过程。" }, { text: "现代书店里的字帖很多", correct: false, explanation: "现代字帖不能直接证明商代发生了什么。" }], conclusion: "甲骨文是研究商代的文字证据；传说和证据要分别看待。" },
      explanation: ["甲骨文包括刻在龟甲、兽骨上的文字，商代留下了许多这样的材料。", "有些记录与当时人们关心的活动有关，但不等于记录了所有人的生活。", "传说可以阅读和欣赏，确认历史事实还要研究实物、文字等证据。"],
      takeaway: "文字是过去的线索，传说需要与历史证据分清。",
      checks: [
        { prompt: "商代甲骨文为什么能帮助我们研究过去？", options: ["因为骨头一定很大", "因为每个字都像今天的字", "因为保存了当时的部分文字记录"], answer: 2, explanation: "它留下了当时的信息，研究者可以结合其他材料来理解。" },
        { prompt: "一部动画说某座古城是神仙一夜建好的，下一步应怎样了解真实建造过程？", options: ["查考古发现和相关记录", "只问动画人物", "直接当作事实"], answer: 0, explanation: "动画情节可以想象，历史解释要寻找能核对的材料。" },
      ],
    }),
    defineLesson({
      id: "history-farming", title: "一粒稻谷，带我们看古人的食物", stageId: "history-settlement", domainId: "history-life", prerequisites: ["history-objects", "history-writing"],
      goal: "把稻谷、农具与古人种植粮食的活动联系起来。",
      why: "学会找证据后，就能问古人怎样获得食物，而不是只记一个遗址名称。",
      story: { title: "浙江河姆渡的发现", text: "河姆渡遗址位于浙江余姚。考古人员发现了栽培稻谷和骨耜等农具。骨耜装上柄，能用来铲土，这些不同线索共同帮助我们认识当时的稻作生活。" },
      activity: { kind: "pairs", instruction: "把河姆渡的发现与它能帮助研究的活动连起来。", pairs: [{ left: "栽培稻谷遗存", right: "种植和利用水稻", explanation: "稻谷遗存是认识古人食物和农业的重要材料。" }, { left: "带加工和使用痕迹的骨耜", right: "铲土等农耕劳动", explanation: "形状、装柄方式和使用痕迹帮助研究它的用途。" }, { left: "陶制炊器", right: "炊煮食物", explanation: "炊器为认识食物加工提供线索，还要结合出土情况判断。" }] },
      explanation: ["农业让一些人通过播种、照料和收获来获得食物。", "河姆渡的稻谷和农具相互补充，比只凭一个故事猜测更可靠。", "会种地不表示不再采集或捕鱼，也不表示所有地方同时采用同一种生活方式。"],
      takeaway: "把几种线索合起来，才能更清楚地认识古人的生活。",
      checks: [
        { prompt: "哪组发现最能帮助研究河姆渡的稻作农业？", options: ["现代篮球与课桌", "栽培稻谷与农具", "只有一张想象画"], answer: 1, explanation: "稻谷与农具分别提供作物和劳动工具的证据。" },
        { prompt: "一个古代村落会种粮食，是否说明居民绝对不再捕鱼？", options: ["是，两种活动不能一起做", "是，因为种地一定更轻松", "不是，还要看鱼骨、工具等材料"], answer: 2, explanation: "不同食物来源可以同时存在，不能用一个发现排除其他活动。" },
      ],
    }),
    defineLesson({
      id: "history-settlements", title: "住在一起，需要怎样合作", stageId: "history-settlement", domainId: "history-life", prerequisites: ["history-farming"],
      goal: "从良渚的城址和水利遗迹，理解聚落生活需要合作。",
      why: "种粮、居住、储存和用水彼此相连，许多人住在一起时，问题会比一家人的生活更复杂。",
      story: { title: "良渚留下的城与水", text: "浙江良渚古城遗址保留了城址、水利系统等线索。这里的人们以稻作农业为重要生活基础。观察不同设施，可以思考他们怎样安排共同生活。" },
      activity: { kind: "pairs", instruction: "把聚落中的事情与需要合作的工作联系起来。", pairs: [{ left: "修筑较大的水利设施", right: "组织人手，搬运和修筑", explanation: "大工程包含许多工作，通常需要安排与合作。" }, { left: "长期种植和储存粮食", right: "照料农田，安排存放", explanation: "粮食不是放下种子就自动装进仓里，需要连续劳动。" }, { left: "研究良渚人的生活", right: "结合城址、水利和出土物", explanation: "不同遗迹能从不同方面提供证据。" }] },
      explanation: ["聚落是人们集中生活的地方，规模和安排可以很不一样。", "良渚的稻作、水利和城址说明，生活中的许多活动互相联系。", "我们可以由工程思考组织与合作，但不能凭一段城墙知道每个人的心情。"],
      takeaway: "认识一个古代聚落，要把食物、住处、用水和合作连起来。",
      checks: [
        { prompt: "研究良渚水利工程时，哪一个问题与共同生活最相关？", options: ["今天谁画的海报最好看", "展柜是什么颜色", "人们怎样组织修筑和维护"], answer: 2, explanation: "较大工程涉及多人的劳动，组织和维护是重要问题。" },
        { prompt: "看到另一处村落遗址，怎样了解其生活？", options: ["照搬良渚的全部结论", "结合房址、食物遗存和工具研究", "只凭村落名字猜"], answer: 1, explanation: "研究方法可以迁移，具体结论仍要依据当地的材料。" },
      ],
    }),
    defineLesson({
      id: "history-paper", title: "把话写下来，也要选择材料", stageId: "history-technology", domainId: "history-life", prerequisites: ["history-writing", "history-settlements"],
      goal: "比较书写材料，并知道技术常在已有经验上改进。",
      why: "人们合作和交流时需要记录；材料的特点，会影响怎样保存和传递信息。",
      story: { title: "带一袋简，还是带几张纸", text: "古人曾在竹木简、丝帛等材料上书写。纸的使用逐渐发展，东汉蔡伦改进了造纸技术。他的贡献建立在已有技术和劳动经验上，不是突然从什么都没有开始。" },
      activity: { kind: "pairs", instruction: "把材料与本课介绍的特点配在一起，想想不同选择。", pairs: [{ left: "许多竹木简", right: "能写字，但成册后较重", explanation: "记录更多内容时，携带材料的重量成为要考虑的问题。" }, { left: "丝帛", right: "可用于书写，但材料较贵", explanation: "能不能大量使用，还与获取材料的成本有关。" }, { left: "纸", right: "轻薄，适合记录与携带", explanation: "造纸技术不断改进，为更多记录和传播提供了条件。" }] },
      explanation: ["选择工具要看用途，也要考虑材料是否容易得到、是否便于携带。", "东汉蔡伦改进造纸技术，改进与最初出现不是同一个意思。", "新材料出现后，旧材料不会马上全部消失；不同用途可能继续采用不同材料。"],
      takeaway: "技术常由很多人的经验积累和改进而来。",
      checks: [
        { prompt: "本课怎样准确介绍蔡伦与造纸技术？", options: ["此前没有任何造纸经验", "他改进了已有造纸技术", "他发明了所有书写材料"], answer: 1, explanation: "改进是在已有技术基础上继续探索，能更准确说明贡献。" },
        { prompt: "今天有电子笔记，还看到有人用纸本，说明什么？", options: ["不同工具可以因用途不同而并存", "所有人必须选同一种工具", "纸本一定没有任何用处"], answer: 0, explanation: "选择与习惯、环境和用途有关，新工具不必立刻替代所有旧工具。" },
      ],
    }),
    defineLesson({
      id: "history-printing", title: "一个个字，怎样反复组合", stageId: "history-technology", domainId: "history-life", prerequisites: ["history-paper"],
      goal: "理解活字可拆开重排的特点，而不是只背发明人的名字。",
      why: "有了书写材料，还要思考怎样复制相同文字；把整块内容拆成可重组的小部分，是一种办法。",
      story: { title: "像排积木一样排字", text: "北宋毕昇制作泥活字，一个字做成一个字模。把字排好可以印刷，印完再拆开，重新排列。印刷还需要制字、上墨等工作，并不是轻轻一按就完成一切。" },
      activity: { kind: "sequence", instruction: "按活字能重新使用的思路，排好这几个步骤。", items: [{ id: "print", text: "上墨后印在纸上" }, { id: "reuse", text: "拆开字模，准备重排" }, { id: "make", text: "准备一个个字模" }, { id: "arrange", text: "按文字内容排成版" }], order: ["make", "arrange", "print", "reuse"], success: "准备字模、排版、印刷、拆开重排。可重新组合，是理解活字的关键。" },
      explanation: ["活字的字模分别制作，可以按不同内容排列。", "北宋毕昇的泥活字是中国古代印刷技术的重要例子。", "活字与雕版各有使用条件，不能简单说新方法在所有情境都更省事。"],
      takeaway: "看懂发明解决了什么问题，比只记住名称更重要。",
      checks: [
        { prompt: "活字最适合用哪句话说明？", options: ["字模能拆开，重新排列", "每印一张就必须毁掉所有字", "只要有纸就不需要排版"], answer: 0, explanation: "字模分别存在、能够重排，是本课的核心特点。" },
        { prompt: "用字母印章先排 CAT，再排 ACT，哪一点像活字的思路？", options: ["同样的小部分可以换顺序组合", "把印章颜色涂成一样", "两次必须使用完全不同的字母"], answer: 0, explanation: "小部件没有全部重新制作，只是组合顺序改变了。" },
      ],
    }),
    defineLesson({
      id: "history-silk-roads", title: "路上交换的，不只是物品", stageId: "history-exchange", domainId: "history-connections", prerequisites: ["history-timeline", "history-printing"],
      goal: "把丝绸之路理解为多条交流路线组成的网络。",
      why: "技术和物品不只留在一个地方，人们的往来把不同地区联系起来。",
      story: { title: "一段又一段的旅程", text: "丝绸之路包含陆路和海路。人们交换丝绸等物品，也交流技艺和想法。许多旅人只走其中一段，货物可以经过不同人的转手继续前行。" },
      activity: { kind: "sort", instruction: "把交流内容分一分，看看路上带来了什么。", categories: ["可以运送的物品", "可以学习交流的知识"], items: [{ text: "一卷丝绸", category: 0, explanation: "丝绸是人们可以携带和交换的物品。" }, { text: "一袋香料", category: 0, explanation: "路线上的货物不只有丝绸。" }, { text: "制作器物的方法", category: 1, explanation: "技艺可以通过示范、学习和记录传播。" }, { text: "不同地方的语言", category: 1, explanation: "交流也让人们接触不同语言和观念。" }], success: "交流既包括货物，也包括技艺和想法；路线是一张逐渐形成的网络。" },
      explanation: ["丝绸之路不是一条笔直、固定不变的公路。", "陆路与海路连接许多地方，交流可能经过很多人、很多段路。", "不同地方的人互相学习，也会按自己的需要改变学到的方法。"],
      takeaway: "往来的路线把物品、知识和人连接起来。",
      checks: [
        { prompt: "哪句话更符合丝绸之路？", options: ["只交换丝绸", "每个商人都从一端走到另一端", "有多条路线，交流多种物品和知识"], answer: 2, explanation: "它是交流网络，不是只走一条路、只卖一种东西。" },
        { prompt: "甲村学会乙村的做陶方法，再按本地材料调整，说明什么？", options: ["学来以后绝对不能改变", "交流中既能学习，也能产生新的做法", "两个村子从此所有事情完全相同"], answer: 1, explanation: "知识传播后，人们仍会根据当地条件继续尝试和改进。" },
      ],
    }),
    defineLesson({
      id: "history-canal", title: "一条水路，连接许多人的生活", stageId: "history-exchange", domainId: "history-connections", prerequisites: ["history-settlements", "history-silk-roads"],
      goal: "从大运河运输粮食的作用，理解交通与生活的联系。",
      why: "路把地方连起来，水路也能运送大量物品；研究交通，要看它服务了哪些生活需要。",
      story: { title: "粮食坐船去远方", text: "中国大运河连接多个地区，向南延伸到浙江。它在不同历史时期逐段修建、整治，曾承担重要粮食运输。水路背后还有造船、装卸和维护等许多人的劳动。" },
      activity: { kind: "pairs", instruction: "把运输中的需要，与相应的劳动配起来。", pairs: [{ left: "让粮食上船", right: "装载和搬运", explanation: "运输不仅是船在行驶，起点和终点也需要人工作。" }, { left: "让航道保持可用", right: "疏浚和维护水道", explanation: "修好以后仍需要持续维护。" }, { left: "了解运河怎样影响生活", right: "研究沿岸运输和城镇资料", explanation: "交通与沿途的劳动、贸易和居住相互联系。" }] },
      explanation: ["大运河是长期建设、维护的水路系统，不是一天一次建成。", "运输粮食等物品，把生产地与需要这些物品的地方连接起来。", "研究大型工程既要看用途，也要记得工程与维护所需的劳动和条件。"],
      takeaway: "认识一条交通路线，要把地方、物品和人的劳动连起来。",
      checks: [
        { prompt: "哪项是大运河历史上的重要作用？", options: ["让粮食不用种就出现", "使所有人住到同一座城", "连接地区、运输粮食等物品"], answer: 2, explanation: "水路促进了物品在地区之间的运送，并未取消生产和劳动。" },
        { prompt: "研究家乡一座老桥，只量桥有多长够吗？", options: ["够，不需要知道其他事", "还可研究它连接哪里、怎样使用和维护", "只看名字就够"], answer: 1, explanation: "用途、联系和劳动能帮助我们理解设施与生活的关系。" },
      ],
    }),
    defineLesson({
      id: "history-change", title: "变了什么，又留下了什么", stageId: "history-explain", domainId: "history-connections", prerequisites: ["history-paper", "history-printing", "history-canal"],
      goal: "围绕同一个问题比较过去与现在，同时找变化和延续。",
      why: "认识了古人的办法后，可以比较今天的生活，但不能只用一个新旧标签代替解释。",
      story: { title: "把消息送给远方的人", text: "有人保存着家人的旧书信，现在也会用手机联系。使用的工具不同，想把事情告诉远方亲人的愿望却可以相同。比较时还要看各自的年代和使用条件。" },
      activity: { kind: "sort", instruction: "在这个书信与手机的例子里，分清变化和延续。", categories: ["发生变化的方面", "可以延续的需要"], items: [{ text: "从纸上书写到屏幕输入", category: 0, explanation: "记录和传送消息的工具、方式发生了变化。" }, { text: "向远方的家人问好", category: 1, explanation: "联系亲人的需要可以在不同时代延续。" }, { text: "有的消息传递得更快", category: 0, explanation: "在适当网络等条件下，通信速度可以改变。" }, { text: "把重要信息表达清楚", category: 1, explanation: "无论用哪种工具，都需要让接收者理解。" }], success: "比较同一件事情，可以同时发现工具的变化与需要的延续。" },
      explanation: ["比较之前，先确定是比较同一种用途，还是完全不同的事情。", "新工具可能带来便利，也有材料、能源或网络等使用条件。", "过去的人会根据当时的条件想办法，不应简单说他们都不聪明。"],
      takeaway: "比较过去与现在，要看条件、变化和延续。",
      checks: [
        { prompt: "比较旧书信与手机消息，哪一项可以是共同点？", options: ["都可以传达对家人的问候", "都必须充电", "都一定立刻送到"], answer: 0, explanation: "共同需要可以延续，具体工具和传送条件却不同。" },
        { prompt: "某种新工具在停电时不能用，老工具仍能工作，应该怎样评价？", options: ["要结合用途和使用条件比较", "所有旧工具都必须扔掉", "所有新工具都没有用"], answer: 0, explanation: "理解变化要看到不同条件下的特点，避免简单地给新旧排高低。" },
      ],
    }),
    defineLesson({
      id: "history-explanation", title: "我为什么这样讲过去", stageId: "history-explain", domainId: "history-sources", prerequisites: ["history-writing", "history-farming", "history-change"],
      goal: "用“我的说法—依据—还不知道什么”讲一个简短历史解释。",
      why: "时间、实物和比较方法连起来，才能形成有依据、又不过度猜测的认识。",
      story: { title: "给河姆渡展览写一句说明", text: "你准备介绍河姆渡人的食物。稻谷遗存、骨耜和其他出土物都值得研究。可以说这些发现支持当时存在稻作农业，但不能据此编出每一家每天吃的菜单。" },
      activity: { kind: "evidence", instruction: "选择支持“当时存在稻作农业”的线索，再看看结论的范围。", passage: "河姆渡遗址发现了栽培稻谷及骨耜等农具。某个现代故事还描写了一家人每天吃三碗米饭，但没有说明这段细节的依据。", clues: [{ text: "出土的栽培稻谷遗存", correct: true, explanation: "这是认识当时水稻种植与利用的实物线索。" }, { text: "相关农具及其使用痕迹", correct: true, explanation: "工具为研究农业劳动提供另一类证据。" }, { text: "没有注明依据的三碗米饭情节", correct: false, explanation: "具体故事细节不能因生动就当作已证实的事实。" }], conclusion: "稻谷和农具共同支持稻作农业的解释，具体每户饮食仍需要更多证据。" },
      explanation: ["先讲清我的说法，再指出支持它的材料，别人才能检查。", "不同材料可以互相补充；如果线索冲突，也应继续核查。", "明确说“这部分还不知道”，比把想象装成事实更诚实。"],
      takeaway: "用证据讲过去，也为仍然不知道的事留下位置。",
      checks: [
        { prompt: "哪句话最像有依据的历史介绍？", options: ["这些稻谷和农具支持当时种稻的认识", "所有细节都能由一件工具知道", "我喜欢这样想，所以一定发生过"], answer: 0, explanation: "这句话说明结论和依据，也没有编造超出材料范围的细节。" },
        { prompt: "研究老学校时，两张照片的说明日期不同，应该怎样做？", options: ["任意挑一个日期", "核对照片来历和其他记录", "把不喜欢的日期藏起来"], answer: 1, explanation: "遇到冲突要检查来源，让结论建立在更清楚的证据上。" },
      ],
    }),
  ],
  sources: [
    { title: "中国国家博物馆：古代中国基本陈列", url: "https://www.chnmuseum.cn/portals/0/web/zt/gudai/default.html?d=123" },
    { title: "中国国家博物馆：甲骨文、金文集粹", url: "https://www.chnmuseum.cn/zl/zlhg/201812/t20181220_32409.shtml" },
    { title: "中国国家博物馆：河姆渡文化考古成果特展", url: "https://www.chnmuseum.cn/portals/0/web/zt/202311hmdwh/" },
    { title: "浙江省博物馆：河姆渡文化与猪纹陶钵", url: "https://www.zhejiangmuseum.com/topic/ydbz/education02.html" },
    { title: "联合国教科文组织：良渚古城遗址", url: "https://whc.unesco.org/en/list/1592" },
    { title: "中国科学技术馆：古代纸张及造纸工艺", url: "https://cstm.cdstm.cn/cszl/hxzg/wmjl/art/2020/art_35113f84365e4fc789f95e54f26fe2d0.html" },
    { title: "中国科学技术馆：仿毕昇活字印刷版", url: "https://www.cdstm.cn/museum/zphc/hxzg2017x/art/2017/art_0871da479c94438ca5cc9031822af8a4.html" },
    { title: "联合国教科文组织：认识丝绸之路", url: "https://www.unesco.org/en/silk-roads/about-silk-roads" },
    { title: "联合国教科文组织：大运河", url: "https://whc.unesco.org/en/list/1443" },
  ],
};
