import { defineQuestion } from "@/lib/question-types";

export const PEP_MATH_G2S1_2025_PACKAGE_ID = "pep-math-g2s1-2025";
export const PEP_MATH_G2S1_2025_CONTENT_VERSION = "2025.1";

const base = (
  unitId: string,
  skillId: string,
  difficulty: "foundation" | "application" | "reasoning",
  questionType: "numeric" | "choice",
  variantGroup: string,
) => ({
  topic: unitId,
  packageId: PEP_MATH_G2S1_2025_PACKAGE_ID,
  contentVersion: PEP_MATH_G2S1_2025_CONTENT_VERSION,
  unitId,
  skillId,
  difficulty,
  questionType,
  variantGroup,
  author: "original" as const,
  reviewStatus: "reviewed" as const,
});

export const pepMathG2S12025Questions = [
  // 第一单元：分类与整理（8 题）
  defineQuestion(
    "p25-u1-s1-01",
    "reasoning",
    "图中的物品按什么标准分成了两类？",
    "物品种类",
    "铅笔和直尺都是学习用品，苹果和梨都是水果，所以是按物品种类分类。",
    "看看每一类物品属于哪一种东西。",
    {
      ...base(
        "u1-classification",
        "classify-by-rule",
        "foundation",
        "choice",
        "classify-rule-purpose",
      ),
      options: ["物品种类", "颜色", "数量"],
      visual: {
        type: "classification",
        items: [
          { label: "铅笔", category: "学习用品" },
          { label: "直尺", category: "学习用品" },
          { label: "苹果", category: "水果" },
          { label: "梨", category: "水果" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s1-02",
    "reasoning",
    "按形状分类，图中有几个圆形？",
    "3",
    "圆片、纽扣和硬币都是圆形，一共有 3 个。",
    "只数标在“圆形”一类里的物品。",
    {
      ...base(
        "u1-classification",
        "classify-by-rule",
        "foundation",
        "numeric",
        "classify-count-shapes",
      ),
      unit: "个",
      visual: {
        type: "classification",
        items: [
          { label: "圆片", category: "圆形" },
          { label: "纽扣", category: "圆形" },
          { label: "硬币", category: "圆形" },
          { label: "三角旗", category: "三角形" },
          { label: "三角尺", category: "三角形" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s1-03",
    "reasoning",
    "这些图形先按颜色分。根据图形本身的特点，还可以按什么分？",
    "形状",
    "图中既有圆形也有三角形，所以还可以按形状分类。",
    "找一找，除了颜色，它们还有什么不同。",
    {
      ...base(
        "u1-classification",
        "classify-by-rule",
        "application",
        "choice",
        "classify-change-rule",
      ),
      options: ["形状", "数量", "用途"],
      visual: {
        type: "classification",
        items: [
          { label: "红圆片", category: "红色" },
          { label: "红三角片", category: "红色" },
          { label: "蓝圆片", category: "蓝色" },
          { label: "蓝三角片", category: "蓝色" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s1-04",
    "reasoning",
    "按“能不能装水”分类，水杯应该和谁分在一类？",
    "水壶",
    "水杯和水壶都能装水，应分在同一类。",
    "想一想每样物品能不能盛水。",
    {
      ...base(
        "u1-classification",
        "classify-by-rule",
        "application",
        "choice",
        "classify-rule-container",
      ),
      options: ["水壶", "毛巾", "跳绳"],
      visual: {
        type: "classification",
        items: [
          { label: "水壶", category: "能装水" },
          { label: "水桶", category: "能装水" },
          { label: "毛巾", category: "不能装水" },
          { label: "跳绳", category: "不能装水" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s2-01",
    "reasoning",
    "图中选择阅读活动的有几人？",
    "3",
    "阅读一类有安安、乐乐和小宇，共 3 人。",
    "找到“阅读”一类，再数名字。",
    {
      ...base(
        "u1-classification",
        "read-classification-results",
        "foundation",
        "numeric",
        "read-result-count",
      ),
      unit: "人",
      visual: {
        type: "classification",
        items: [
          { label: "安安", category: "阅读" },
          { label: "乐乐", category: "阅读" },
          { label: "小宇", category: "阅读" },
          { label: "可可", category: "跳绳" },
          { label: "明明", category: "跳绳" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s2-02",
    "reasoning",
    "图中哪一类物品最多？",
    "文具",
    "文具有 4 件，玩具有 2 件，图书有 1 本，所以文具最多。",
    "分别数一数三类物品。",
    {
      ...base(
        "u1-classification",
        "read-classification-results",
        "foundation",
        "choice",
        "read-result-most",
      ),
      options: ["文具", "玩具", "图书"],
      visual: {
        type: "classification",
        items: [
          { label: "铅笔", category: "文具" },
          { label: "橡皮", category: "文具" },
          { label: "直尺", category: "文具" },
          { label: "卷笔刀", category: "文具" },
          { label: "小车", category: "玩具" },
          { label: "积木", category: "玩具" },
          { label: "故事书", category: "图书" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s2-03",
    "reasoning",
    "图中晴天比雨天多几天？",
    "2",
    "晴天有 5 天，雨天有 3 天，5 − 3 = 2，所以多 2 天。",
    "先分别数出晴天和雨天。",
    {
      ...base(
        "u1-classification",
        "read-classification-results",
        "application",
        "numeric",
        "read-result-difference",
      ),
      unit: "天",
      visual: {
        type: "classification",
        items: [
          { label: "周一", category: "晴天" },
          { label: "周二", category: "晴天" },
          { label: "周三", category: "晴天" },
          { label: "周四", category: "晴天" },
          { label: "周五", category: "晴天" },
          { label: "周六", category: "雨天" },
          { label: "周日", category: "雨天" },
          { label: "下周一", category: "雨天" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u1-s2-04",
    "reasoning",
    "绘画有 3 人，合唱有 2 人。合唱再来 1 人后，两组怎样？",
    "一样多",
    "合唱原有 2 人，再来 1 人是 3 人，和绘画组一样多。",
    "先算合唱组后来有几人。",
    {
      ...base(
        "u1-classification",
        "read-classification-results",
        "reasoning",
        "choice",
        "read-result-change",
      ),
      options: ["绘画多", "合唱多", "一样多"],
      visual: {
        type: "classification",
        items: [
          { label: "小青", category: "绘画" },
          { label: "小禾", category: "绘画" },
          { label: "小川", category: "绘画" },
          { label: "小满", category: "合唱" },
          { label: "小雨", category: "合唱" },
        ],
      },
    },
  ),

  // 第二单元：1～6 的表内乘法（12 题）
  defineQuestion(
    "p25-u2-s3-01",
    "multiplication",
    "有 3 组圆点，每组 2 个，一共有几个？",
    "6",
    "3 个 2 相加是 2 + 2 + 2 = 6，也可以写成 3 × 2 = 6。",
    "数一数有几组，每组有几个。",
    {
      ...base(
        "u2-multiplication-1-6",
        "understand-multiplication",
        "foundation",
        "numeric",
        "equal-groups-total",
      ),
      unit: "个",
      visual: { type: "groups", groups: 3, each: 2 },
    },
  ),
  defineQuestion(
    "p25-u2-s3-02",
    "multiplication",
    "4 组圆点，每组 5 个，可以写成哪道连加算式？",
    "5 + 5 + 5 + 5",
    "每组有 5 个，共 4 组，所以是 4 个 5 相加。",
    "每一组贡献一个相同的加数。",
    {
      ...base(
        "u2-multiplication-1-6",
        "understand-multiplication",
        "foundation",
        "choice",
        "equal-groups-addition",
      ),
      options: ["5 + 5 + 5 + 5", "4 + 5", "4 + 4 + 4 + 4 + 4 + 4"],
      visual: { type: "groups", groups: 4, each: 5 },
    },
  ),
  defineQuestion(
    "p25-u2-s3-03",
    "multiplication",
    "6 个篮子，每个篮子有 3 个球，求总数应列哪道算式？",
    "6 × 3",
    "6 个篮子就是 6 组，每组 3 个，应列 6 × 3。",
    "把“几个几”写成乘法。",
    {
      ...base(
        "u2-multiplication-1-6",
        "understand-multiplication",
        "application",
        "choice",
        "equal-groups-expression",
      ),
      options: ["6 × 3", "6 + 3", "6 − 3"],
      visual: { type: "groups", groups: 6, each: 3 },
    },
  ),
  defineQuestion(
    "p25-u2-s3-04",
    "multiplication",
    "4 盒每盒 3 支笔，3 袋每袋 4 张卡片。两种物品的总数怎样？",
    "一样多",
    "4 × 3 = 12，3 × 4 = 12，所以两种物品的总数一样多。",
    "分别用乘法算出两边的总数。",
    {
      ...base(
        "u2-multiplication-1-6",
        "understand-multiplication",
        "reasoning",
        "choice",
        "equal-groups-compare",
      ),
      options: ["笔多", "卡片多", "一样多"],
    },
  ),
  defineQuestion(
    "p25-u2-s4-01",
    "multiplication",
    "5 × 6 = ?",
    "30",
    "五六三十，所以 5 × 6 = 30。",
    "想一想“五六”的乘法口诀。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-facts-2-6",
        "foundation",
        "numeric",
        "facts-direct-5-6",
      ),
    },
  ),
  defineQuestion(
    "p25-u2-s4-02",
    "multiplication",
    "2 × 6 = ?",
    "12",
    "二六十二，所以 2 × 6 = 12。",
    "想一想“二六”的乘法口诀。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-facts-2-6",
        "foundation",
        "numeric",
        "facts-direct-2-6",
      ),
    },
  ),
  defineQuestion(
    "p25-u2-s4-03",
    "multiplication",
    "6 × 多少 = 24？",
    "4",
    "四六二十四，所以 6 × 4 = 24。",
    "哪句口诀的结果是 24？",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-facts-2-6",
        "application",
        "numeric",
        "facts-missing-factor",
      ),
    },
  ),
  defineQuestion(
    "p25-u2-s4-04",
    "multiplication",
    "下面哪道算式的结果是 24？",
    "4 × 6",
    "四六二十四，所以 4 × 6 的结果是 24。",
    "分别想一想三句乘法口诀。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-facts-2-6",
        "application",
        "choice",
        "facts-select-expression",
      ),
      options: ["4 × 6", "5 × 6", "6 × 6"],
    },
  ),
  defineQuestion(
    "p25-u2-s5-01",
    "multiplication",
    "3 个篮子里各有 5 个橘子，一共有多少个橘子？",
    "15",
    "3 个 5 相加，用乘法算：3 × 5 = 15。",
    "有 3 组，每组 5 个。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-applications",
        "foundation",
        "numeric",
        "multiply-context-total",
      ),
      unit: "个",
      visual: { type: "groups", groups: 3, each: 5 },
    },
  ),
  defineQuestion(
    "p25-u2-s5-02",
    "multiplication",
    "6 张桌子，每张坐 4 人，一共能坐多少人？",
    "24",
    "6 组，每组 4 人，6 × 4 = 24。",
    "用桌子数乘每张桌子坐的人数。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-applications",
        "foundation",
        "numeric",
        "multiply-context-capacity",
      ),
      unit: "人",
      visual: { type: "groups", groups: 6, each: 4 },
    },
  ),
  defineQuestion(
    "p25-u2-s5-03",
    "multiplication",
    "5 排座位，每排 6 个，其中 4 个空着。坐了多少人？",
    "26",
    "先算共有 5 × 6 = 30 个座位，再算 30 − 4 = 26。",
    "先求座位总数，再去掉空座位。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-applications",
        "application",
        "numeric",
        "multiply-context-two-step",
      ),
      unit: "人",
    },
  ),
  defineQuestion(
    "p25-u2-s5-04",
    "multiplication",
    "4 袋珠子，每袋 6 颗。拿走 1 袋后，还剩多少颗？",
    "18",
    "拿走 1 袋后还剩 3 袋，3 × 6 = 18，所以还剩 18 颗。",
    "先想拿走 1 袋后还剩几袋。",
    {
      ...base(
        "u2-multiplication-1-6",
        "multiplication-applications",
        "reasoning",
        "numeric",
        "multiply-context-remove-group",
      ),
      unit: "颗",
      visual: { type: "groups", groups: 4, each: 6 },
    },
  ),

  // 第三单元：1～6 的表内除法（12 题）
  defineQuestion(
    "p25-u3-s6-01",
    "multiplication",
    "12 块饼干平均分给 3 人，每人分到几块？",
    "4",
    "把 12 平均分成 3 份，12 ÷ 3 = 4，每人 4 块。",
    "平均分后，每一份要同样多。",
    {
      ...base(
        "u3-division-1-6",
        "understand-division",
        "foundation",
        "numeric",
        "division-equal-share",
      ),
      unit: "块",
      visual: { type: "groups", groups: 3, each: 4 },
    },
  ),
  defineQuestion(
    "p25-u3-s6-02",
    "multiplication",
    "15 朵花，每 5 朵插一瓶，需要几个花瓶？",
    "3",
    "15 里面有 3 个 5，15 ÷ 5 = 3，需要 3 个花瓶。",
    "看 15 里面能分出几组 5。",
    {
      ...base(
        "u3-division-1-6",
        "understand-division",
        "foundation",
        "numeric",
        "division-grouping",
      ),
      unit: "个",
      visual: { type: "groups", groups: 3, each: 5 },
    },
  ),
  defineQuestion(
    "p25-u3-s6-03",
    "multiplication",
    "18 个球平均装进 6 个盒子，求每盒几个，应列哪道算式？",
    "18 ÷ 6",
    "把 18 平均分成 6 份，应列 18 ÷ 6。",
    "总数除以平均分成的份数。",
    {
      ...base(
        "u3-division-1-6",
        "understand-division",
        "application",
        "choice",
        "division-select-expression",
      ),
      options: ["18 ÷ 6", "18 − 6", "18 + 6"],
      visual: { type: "groups", groups: 6, each: 3 },
    },
  ),
  defineQuestion(
    "p25-u3-s6-04",
    "multiplication",
    "12 个球，每袋装 4 个：12 ÷ 4 = 3（袋）；12 个球平均装进 4 袋：12 ÷ 4 = 3（个）。两个“3”表示的意思相同吗？",
    "不相同",
    "第一题的 3 表示 3 袋；第二题的 3 表示每袋 3 个。数相同，表示的意思不同。",
    "注意答案后面的单位和问题在问什么。",
    {
      ...base(
        "u3-division-1-6",
        "understand-division",
        "reasoning",
        "choice",
        "division-compare-meanings",
      ),
      options: ["相同", "不相同"],
    },
  ),
  defineQuestion(
    "p25-u3-s7-01",
    "multiplication",
    "24 ÷ 6 = ?",
    "4",
    "四六二十四，所以 24 ÷ 6 = 4。",
    "想哪句乘法口诀里有 6 和 24。",
    {
      ...base(
        "u3-division-1-6",
        "division-facts-1-6",
        "foundation",
        "numeric",
        "division-facts-direct-6",
      ),
    },
  ),
  defineQuestion(
    "p25-u3-s7-02",
    "multiplication",
    "12 ÷ 2 = ?",
    "6",
    "二六十二，所以 12 ÷ 2 = 6。",
    "想一想：2 乘几等于 12？",
    {
      ...base(
        "u3-division-1-6",
        "division-facts-1-6",
        "foundation",
        "numeric",
        "division-facts-direct-2",
      ),
    },
  ),
  defineQuestion(
    "p25-u3-s7-03",
    "multiplication",
    "18 ÷ 多少 = 6？",
    "3",
    "三六十八，所以 18 ÷ 3 = 6。",
    "哪句口诀的积是 18？",
    {
      ...base(
        "u3-division-1-6",
        "division-facts-1-6",
        "application",
        "numeric",
        "division-facts-missing-divisor",
      ),
    },
  ),
  defineQuestion(
    "p25-u3-s7-04",
    "multiplication",
    "下面哪道算式的商是 4？",
    "20 ÷ 5",
    "四五二十，所以 20 ÷ 5 = 4。",
    "分别想一想：除数乘几等于被除数？",
    {
      ...base(
        "u3-division-1-6",
        "division-facts-1-6",
        "application",
        "choice",
        "division-facts-select",
      ),
      options: ["20 ÷ 5", "18 ÷ 6", "12 ÷ 2"],
    },
  ),
  defineQuestion(
    "p25-u3-s8-01",
    "multiplication",
    "18 个苹果平均放在 6 个盘子里，每盘几个？",
    "3",
    "18 ÷ 6 = 3，每盘放 3 个。",
    "总数除以盘子数。",
    {
      ...base(
        "u3-division-1-6",
        "division-applications",
        "foundation",
        "numeric",
        "division-application-share",
      ),
      unit: "个",
      visual: { type: "groups", groups: 6, each: 3 },
    },
  ),
  defineQuestion(
    "p25-u3-s8-02",
    "multiplication",
    "20 颗纽扣，每 4 颗装一袋，可以装几袋？",
    "5",
    "20 里面有 5 个 4，20 ÷ 4 = 5。",
    "想一想四几二十。",
    {
      ...base(
        "u3-division-1-6",
        "division-applications",
        "foundation",
        "numeric",
        "division-application-groups",
      ),
      unit: "袋",
      visual: { type: "groups", groups: 5, each: 4 },
    },
  ),
  defineQuestion(
    "p25-u3-s8-03",
    "multiplication",
    "24 厘米彩带，每 6 厘米剪一段，可以剪成几段？",
    "4",
    "24 ÷ 6 = 4，可以剪成 4 段。",
    "看 24 里面有几个 6。",
    {
      ...base(
        "u3-division-1-6",
        "division-applications",
        "application",
        "numeric",
        "division-application-length-groups",
      ),
      unit: "段",
    },
  ),
  defineQuestion(
    "p25-u3-s8-04",
    "multiplication",
    "24 本书每层放 6 本，需要几层？另 24 本书平均放在 4 层，每层几本？",
    "4 层和 6 本",
    "第一题 24 ÷ 6 = 4 层；第二题 24 ÷ 4 = 6 本。",
    "先看每题求的是份数还是每份数。",
    {
      ...base(
        "u3-division-1-6",
        "division-applications",
        "application",
        "choice",
        "division-application-compare-types",
      ),
      options: ["4 层和 6 本", "6 层和 4 本", "都是 4"],
    },
  ),

  // 第四单元：厘米和米（8 题）
  defineQuestion(
    "p25-u4-s9-01",
    "length",
    "测量一支铅笔的长度，用哪个单位更合适？",
    "厘米",
    "铅笔比较短，用厘米作单位更合适。",
    "比较铅笔和教室的长短。",
    {
      ...base(
        "u4-centimeter-meter",
        "choose-and-estimate-length",
        "foundation",
        "choice",
        "length-choose-cm",
      ),
      options: ["厘米", "米", "千克"],
    },
  ),
  defineQuestion(
    "p25-u4-s9-02",
    "length",
    "教室长约 8 什么？",
    "米",
    "教室比较长，用米作单位合适，所以约长 8 米。",
    "把教室的长度和铅笔、大人的一步比较一比。",
    {
      ...base(
        "u4-centimeter-meter",
        "choose-and-estimate-length",
        "foundation",
        "choice",
        "length-choose-m",
      ),
      options: ["厘米", "米", "个"],
    },
  ),
  defineQuestion(
    "p25-u4-s9-03",
    "length",
    "一扇门的高度大约是多少？",
    "2 米",
    "门比小朋友高一些，高度约 2 米比较合适。",
    "先想一想小朋友大约有多高。",
    {
      ...base(
        "u4-centimeter-meter",
        "choose-and-estimate-length",
        "application",
        "choice",
        "length-estimate-door",
      ),
      options: ["2 厘米", "20 厘米", "2 米"],
    },
  ),
  defineQuestion(
    "p25-u4-s9-04",
    "length",
    "下面哪组估计都比较合适？",
    "铅笔长 18 厘米，教室长 8 米",
    "铅笔通常十几厘米长，教室通常几米长，这组估计合理。",
    "把每个物体和生活中见过的长度比较。",
    {
      ...base(
        "u4-centimeter-meter",
        "choose-and-estimate-length",
        "reasoning",
        "choice",
        "length-estimate-pair",
      ),
      options: [
        "铅笔长 18 厘米，教室长 8 米",
        "铅笔长 18 米，教室长 8 厘米",
        "铅笔长 1 厘米，教室长 1 米",
      ],
    },
  ),
  defineQuestion(
    "p25-u4-s10-01",
    "length",
    "尺子上物体左端对着 2，右端对着 8。物体长几厘米？",
    "6",
    "右端刻度减左端刻度：8 − 2 = 6 厘米。",
    "不是从 0 开始，要用两端刻度相减。",
    {
      ...base(
        "u4-centimeter-meter",
        "measure-convert-apply-length",
        "foundation",
        "numeric",
        "length-ruler-nonzero",
      ),
      unit: "厘米",
      visual: { type: "ruler", start: 2, end: 8, unit: "厘米" },
    },
  ),
  defineQuestion(
    "p25-u4-s10-02",
    "length",
    "1 米等于多少厘米？",
    "100",
    "1 米 = 100 厘米。",
    "想一想一把米尺上有多少个 1 厘米。",
    {
      ...base(
        "u4-centimeter-meter",
        "measure-convert-apply-length",
        "foundation",
        "numeric",
        "length-convert-m-cm",
      ),
      unit: "厘米",
    },
  ),
  defineQuestion(
    "p25-u4-s10-03",
    "length",
    "一根 1 米长的彩带剪去 30 厘米，还剩多少厘米？",
    "70",
    "1 米是 100 厘米，100 − 30 = 70 厘米。",
    "先把 1 米换成厘米。",
    {
      ...base(
        "u4-centimeter-meter",
        "measure-convert-apply-length",
        "application",
        "numeric",
        "length-convert-subtract",
      ),
      unit: "厘米",
    },
  ),
  defineQuestion(
    "p25-u4-s10-04",
    "length",
    "尺子上铅笔左端对着 3，右端对着 12；橡皮长 5 厘米。铅笔比橡皮长多少厘米？",
    "4",
    "铅笔长 12 − 3 = 9 厘米，再算 9 − 5 = 4 厘米。",
    "先算铅笔的长度，再和橡皮比较。",
    {
      ...base(
        "u4-centimeter-meter",
        "measure-convert-apply-length",
        "application",
        "numeric",
        "length-ruler-compare",
      ),
      unit: "厘米",
      visual: { type: "ruler", start: 3, end: 12, unit: "厘米" },
    },
  ),

  // 第五单元：7～9 的表内乘除法（12 题）
  defineQuestion(
    "p25-u5-s11-01",
    "multiplication",
    "7 × 8 = ?",
    "56",
    "七八五十六，所以 7 × 8 = 56。",
    "想一想“七八”的乘法口诀。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "facts-7-9",
        "foundation",
        "numeric",
        "facts-7-8-multiply",
      ),
    },
  ),
  defineQuestion(
    "p25-u5-s11-02",
    "multiplication",
    "9 × 6 = ?",
    "54",
    "六九五十四，所以 9 × 6 = 54。",
    "想一想“六九”的乘法口诀。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "facts-7-9",
        "foundation",
        "numeric",
        "facts-9-6-multiply",
      ),
    },
  ),
  defineQuestion(
    "p25-u5-s11-03",
    "multiplication",
    "56 ÷ 7 = ?",
    "8",
    "七八五十六，所以 56 ÷ 7 = 8。",
    "想一想：7 乘几等于 56？",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "facts-7-9",
        "application",
        "numeric",
        "facts-7-division",
      ),
    },
  ),
  defineQuestion(
    "p25-u5-s11-04",
    "multiplication",
    "下面哪组算式的结果都是 8？",
    "64 ÷ 8 和 72 ÷ 9",
    "八八六十四、八九七十二，所以两道除法的商都是 8。",
    "分别用 8 和 9 的乘法口诀求商。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "facts-7-9",
        "application",
        "choice",
        "facts-8-9-division-pair",
      ),
      options: ["64 ÷ 8 和 72 ÷ 9", "56 ÷ 8 和 63 ÷ 7", "49 ÷ 7 和 54 ÷ 9"],
    },
  ),
  defineQuestion(
    "p25-u5-s12-01",
    "multiplication",
    "根据 7 × 8 = 56，可以直接得到哪道除法算式？",
    "56 ÷ 7 = 8",
    "乘法和除法互相关联，7 × 8 = 56，所以 56 ÷ 7 = 8。",
    "积作被除数，一个因数作除数。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "inverse-multiplication-division",
        "foundation",
        "choice",
        "inverse-from-product",
      ),
      options: ["56 ÷ 7 = 8", "56 − 7 = 8", "56 ÷ 8 = 6"],
    },
  ),
  defineQuestion(
    "p25-u5-s12-02",
    "multiplication",
    "已知 9 × 4 = 36，那么 36 ÷ 4 等于多少？",
    "9",
    "因为 9 × 4 = 36，所以 36 ÷ 4 = 9。",
    "用乘法算式里的积和因数来想。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "inverse-multiplication-division",
        "foundation",
        "numeric",
        "inverse-find-quotient",
      ),
    },
  ),
  defineQuestion(
    "p25-u5-s12-03",
    "multiplication",
    "哪组算式能表示 8 行、每行 7 个圆点之间的关系？",
    "8 × 7 = 56，56 ÷ 8 = 7",
    "8 行每行 7 个，共 56 个；把 56 平均分成 8 行，每行 7 个。",
    "乘法求总数，除法可以反过来求每份数。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "inverse-multiplication-division",
        "application",
        "choice",
        "inverse-context-equations",
      ),
      options: [
        "8 × 7 = 56，56 ÷ 8 = 7",
        "8 + 7 = 15，56 ÷ 7 = 7",
        "8 × 7 = 54，54 ÷ 8 = 7",
      ],
    },
  ),
  defineQuestion(
    "p25-u5-s12-04",
    "multiplication",
    "同一个数填入两处：多少 × 8 = 72，72 ÷ 多少 = 8？",
    "9",
    "八九七十二，所以 9 × 8 = 72，72 ÷ 9 = 8。",
    "先看哪个数和 8 相乘能得到 72。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "inverse-multiplication-division",
        "reasoning",
        "numeric",
        "inverse-shared-number",
      ),
    },
  ),
  defineQuestion(
    "p25-u5-s13-01",
    "multiplication",
    "7 张贴纸一组，摆 8 组，一共有多少张？",
    "56",
    "7 × 8 = 56，一共有 56 张贴纸。",
    "有 8 组，每组 7 张。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "multiplication-division-applications",
        "foundation",
        "numeric",
        "facts-application-total",
      ),
      unit: "张",
    },
  ),
  defineQuestion(
    "p25-u5-s13-02",
    "multiplication",
    "63 盏小灯，每 9 盏挂一排，可以挂几排？",
    "7",
    "63 ÷ 9 = 7，可以挂 7 排。",
    "想一想：9 乘几等于 63？",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "multiplication-division-applications",
        "foundation",
        "numeric",
        "facts-application-groups",
      ),
      unit: "排",
    },
  ),
  defineQuestion(
    "p25-u5-s13-03",
    "multiplication",
    "72 张卡片平均分给 8 组，每组再补发 2 张。现在每组有多少张？",
    "11",
    "先算 72 ÷ 8 = 9，每组原有 9 张；再算 9 + 2 = 11 张。",
    "先求平均分后每组有几张，再加上补发的卡片。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "multiplication-division-applications",
        "application",
        "numeric",
        "facts-application-share-add",
      ),
      unit: "张",
    },
  ),
  defineQuestion(
    "p25-u5-s13-04",
    "multiplication",
    "56 棵幼苗每行种 8 棵，又添种完整的一行。现在共有多少棵？",
    "64",
    "每行 8 棵，再添一行就是多 8 棵，56 + 8 = 64。也可想 7 行变成 8 行，8 × 8 = 64。",
    "先用 56 ÷ 8 想原来有几行。",
    {
      ...base(
        "u5-multiplication-division-7-9",
        "multiplication-division-applications",
        "reasoning",
        "numeric",
        "facts-application-add-row",
      ),
      unit: "棵",
    },
  ),

  // 第六单元：复习与关联（4 题）
  defineQuestion(
    "p25-u6-s14-01",
    "reasoning",
    "3 盒蜡笔，每盒 6 支，求一共有多少支，应该用什么运算？",
    "乘法",
    "求 3 个 6 是多少，用乘法计算。",
    "想一想：这是在求几个相同数量的和，还是在平均分？",
    {
      ...base(
        "u6-review-connections",
        "connect-and-apply",
        "foundation",
        "choice",
        "review-choose-operation",
      ),
      options: ["乘法", "除法", "减法"],
      visual: { type: "groups", groups: 3, each: 6 },
    },
  ),
  defineQuestion(
    "p25-u6-s14-02",
    "reasoning",
    "两条彩带各长 8 厘米，首尾相接且不重叠，共长多少厘米？",
    "16",
    "2 个 8 厘米相加，2 × 8 = 16 厘米。",
    "把两条同样长的彩带看成 2 个 8。",
    {
      ...base(
        "u6-review-connections",
        "connect-and-apply",
        "foundation",
        "numeric",
        "review-multiply-length",
      ),
      unit: "厘米",
    },
  ),
  defineQuestion(
    "p25-u6-s14-03",
    "reasoning",
    "阅读组 3 人、绘画组 4 人，每人发 2 张卡片，共需多少张？",
    "14",
    "先算共有 3 + 4 = 7 人，再算 7 × 2 = 14 张。",
    "先把两组人数合起来。",
    {
      ...base(
        "u6-review-connections",
        "connect-and-apply",
        "application",
        "numeric",
        "review-classify-multiply",
      ),
      unit: "张",
      visual: {
        type: "classification",
        items: [
          { label: "小江", category: "阅读" },
          { label: "小云", category: "阅读" },
          { label: "小树", category: "阅读" },
          { label: "小米", category: "绘画" },
          { label: "小舟", category: "绘画" },
          { label: "小竹", category: "绘画" },
          { label: "小星", category: "绘画" },
        ],
      },
    },
  ),
  defineQuestion(
    "p25-u6-s14-04",
    "reasoning",
    "32 面小旗，每 8 面穿成一串。每串挂在 1 米绳上，共需几米绳？",
    "4",
    "32 ÷ 8 = 4，需要 4 串；每串用 1 米绳，共需 4 米。",
    "先求可以穿成几串。",
    {
      ...base(
        "u6-review-connections",
        "connect-and-apply",
        "reasoning",
        "numeric",
        "review-division-length",
      ),
      unit: "米",
      visual: { type: "groups", groups: 4, each: 8 },
    },
  ),
];

export const pepMathG2S12025Package = {
  id: PEP_MATH_G2S1_2025_PACKAGE_ID,
  contentVersion: PEP_MATH_G2S1_2025_CONTENT_VERSION,
  title: "二年级上册数学（人教版 2025 知识框架适配）",
  units: [
    { id: "u1-classification", title: "分类与整理" },
    { id: "u2-multiplication-1-6", title: "1～6 的表内乘法" },
    { id: "u3-division-1-6", title: "1～6 的表内除法" },
    { id: "u4-centimeter-meter", title: "厘米和米" },
    {
      id: "u5-multiplication-division-7-9",
      title: "7～9 的表内乘除法",
    },
    { id: "u6-review-connections", title: "复习与关联" },
  ],
  questions: pepMathG2S12025Questions,
};
