// Generated by scripts/generate-learning-media.py; keep captions and copy in sync.
export type LearningVideoId = "count" | "day-night" | "water-cycle";

export type LearningVideo = {
  id: LearningVideoId;
  title: string;
  description: string;
  src: string;
  poster: string;
  captions: string;
  durationSeconds: number;
  transcript: string[];
  note: string;
};

export const learningVideos: Record<LearningVideoId, LearningVideo> = {
  "count": {
    "id": "count",
    "title": "五个光点，一个也不漏",
    "description": "跟着光点逐个数，再看看换了位置，数量会不会变。",
    "src": "/media/learning/v1/count.mp4",
    "poster": "/media/learning/v1/count.webp",
    "captions": "/media/learning/v1/count.zh.vtt",
    "durationSeconds": 24,
    "transcript": [
      "这里有几个光点？我们一个一个地数。",
      "一，点亮第一个。",
      "二，再数一个。",
      "三，每个只数一次。",
      "四，不要漏掉。",
      "五！所有光点都数到了。",
      "最后数到五，就知道一共有五个。",
      "换了位置，没有增加，也没有减少。还是五个！"
    ],
    "note": "原创静音动画。光点只是计数对象；看过短片不会自动记为掌握。"
  },
  "day-night": {
    "id": "day-night",
    "title": "我的白天，去了哪里？",
    "description": "盯住地球上的同一个地点，看它怎样从白天转到黑夜。",
    "src": "/media/learning/v1/day-night.mp4",
    "poster": "/media/learning/v1/day-night.webp",
    "captions": "/media/learning/v1/day-night.zh.vtt",
    "durationSeconds": 28,
    "transcript": [
      "太阳一直在照亮地球。黄色圆点，是我们观察的同一个地点。",
      "地球在自转，这个地点也跟着一起转动。",
      "转到背向太阳的一边，这个地点就进入黑夜。",
      "地球继续转动，这个地点又来到朝向太阳的一边。",
      "白天又来了！昼夜交替，和地球自转有关。"
    ],
    "note": "原创静音示意动画。从北极上方看地球，黄色圆点代表同一个地点。大小、距离和转速均作简化；本片只解释自转与昼夜。"
  },
  "water-cycle": {
    "id": "water-cycle",
    "title": "跟着水，去旅行",
    "description": "从水面出发，认识蒸发、云、降水和汇流之间的联系。",
    "src": "/media/learning/v1/water-cycle.mp4",
    "poster": "/media/learning/v1/water-cycle.webp",
    "captions": "/media/learning/v1/water-cycle.zh.vtt",
    "durationSeconds": 32,
    "transcript": [
      "太阳提供能量，水的旅行开始了。",
      "液态水蒸发，变成看不见的水蒸气。图中的虚线只是帮助理解的示意。",
      "水蒸气遇冷，可凝结成小水滴。云里也可能有小冰晶。",
      "小水滴或冰晶不断长大，在合适条件下形成降水，比如雨。",
      "部分雨水沿地面流动，汇入河流、湖泊和海洋。",
      "水还会继续旅行。这只是水循环中的一条路径。"
    ],
    "note": "原创静音示意动画。虚线表示看不见的水蒸气的移动；本片只展示水循环的一条路径，还存在渗入地下、植物蒸腾等路径。过程、距离和时间均作简化。"
  }
};

export function getLearningVideo(id: LearningVideoId): LearningVideo {
  return learningVideos[id];
}
