import type { Question } from "./catalog";
export type GradedQuestion = Question & { answer: string; explanation: string };
const q = (
  id: string,
  topic: string,
  prompt: string,
  answer: string,
  explanation: string,
  hint: string,
  extra: Partial<Question> = {},
): GradedQuestion => ({
  id,
  topic,
  prompt,
  answer,
  explanation,
  hint,
  ...extra,
});
export const questions: GradedQuestion[] = [
  q(
    "add-1",
    "addition",
    "小禾有 28 张贴纸，又得到 17 张。现在一共有多少张？",
    "45",
    "先算 28 + 10 = 38，再算 38 + 7 = 45，所以一共有 45 张。",
    "先加十位，再加个位。",
    { unit: "张" },
  ),
  q(
    "add-2",
    "addition",
    "46 + 29 = ?",
    "75",
    "46 + 20 = 66，66 + 9 = 75。个位满十，要向十位进一。",
    "个位相加满十了吗？",
  ),
  q(
    "add-3",
    "addition",
    "72 − 38 = ?",
    "34",
    "72 − 30 = 42，42 − 8 = 34。也可以想：38 + 34 = 72。",
    "个位不够减，可以从十位借一。",
  ),
  q(
    "add-4",
    "addition",
    "图书角原来有 53 本书，借走 16 本，还剩多少本？",
    "37",
    "53 − 10 = 43，43 − 6 = 37，还剩 37 本。",
    "借走后数量会变多还是变少？",
    { unit: "本" },
  ),
  q(
    "add-5",
    "addition",
    "35 + 27 − 18 = ?",
    "44",
    "从左往右算：35 + 27 = 62，再算 62 − 18 = 44。",
    "先算加法，再减去 18。",
  ),
  q(
    "add-6",
    "addition",
    "小林有 36 颗珠子，比小禾多 9 颗。小禾有多少颗？",
    "27",
    "小禾比小林少 9 颗，所以 36 − 9 = 27。",
    "先想清楚谁多、谁少。",
    { unit: "颗" },
  ),
  q(
    "mul-1",
    "multiplication",
    "每组有 3 个圆点，4 组一共有多少个？",
    "12",
    "4 个 3 相加：3 + 3 + 3 + 3 = 12，也可以用 4 × 3 = 12。",
    "数一数有几组，每组有几个。",
    { unit: "个", visual: { type: "groups", groups: 4, each: 3 } },
  ),
  q(
    "mul-2",
    "multiplication",
    "6 × 7 = ?",
    "42",
    "六七四十二，所以 6 × 7 = 42。",
    "想一想“六七”的乘法口诀。",
  ),
  q(
    "mul-3",
    "multiplication",
    "每盒有 5 支铅笔，6 盒一共有多少支？",
    "30",
    "6 个 5 相加，用乘法：5 × 6 = 30。",
    "同样多的几组，可以用乘法。",
    { unit: "支" },
  ),
  q(
    "mul-4",
    "multiplication",
    "8 × 9 = ?",
    "72",
    "八九七十二，所以 8 × 9 = 72。",
    "用“八九”的口诀来帮忙。",
  ),
  q(
    "mul-5",
    "multiplication",
    "3 × 4 + 2 = ?",
    "14",
    "先算 3 × 4 = 12，再算 12 + 2 = 14。",
    "先求 3 个 4，再加 2。",
  ),
  q(
    "mul-6",
    "multiplication",
    "4 个 6 相加，结果是多少？",
    "24",
    "4 个 6 是 6 + 6 + 6 + 6 = 24，也就是 4 × 6 = 24。",
    "“4 个 6”不是“4 加 6”。",
  ),
  q(
    "len-1",
    "length",
    "测量一支铅笔的长度，用哪个单位更合适？",
    "厘米",
    "铅笔比较短，用“厘米”表示更合适。",
    "比较一下铅笔和教室的长度。",
    { options: ["厘米", "米"] },
  ),
  q(
    "len-2",
    "length",
    "1 米 = 多少厘米？",
    "100",
    "1 米 = 100 厘米。这是米和厘米之间的关系。",
    "想一想米尺上有多少个 1 厘米。",
    { unit: "厘米" },
  ),
  q(
    "len-3",
    "length",
    "一根绳子长 80 厘米，剪去 25 厘米，还剩多少厘米？",
    "55",
    "80 − 25 = 55，所以还剩 55 厘米。",
    "总长度减去剪掉的长度。",
    { unit: "厘米" },
  ),
  q(
    "len-4",
    "length",
    "尺子上，橡皮左端对着 2 厘米，右端对着 6 厘米。橡皮长多少厘米？",
    "4",
    "右端刻度减去左端刻度：6 − 2 = 4 厘米。",
    "不是从 0 开始量，要用两端刻度相减。",
    { unit: "厘米" },
  ),
  q(
    "angle-1",
    "angles",
    "一个角有几个顶点？",
    "1",
    "一个角有 1 个顶点和 2 条边。",
    "想一想，两条边从哪里出发。",
    { unit: "个" },
  ),
  q(
    "angle-2",
    "angles",
    "长方形的四个角都是什么角？",
    "直角",
    "长方形的四个角都是直角，可以用三角尺上的直角检查。",
    "看看书本封面的四个角。",
    { options: ["锐角", "直角", "钝角"] },
  ),
  q(
    "angle-3",
    "angles",
    "比直角小的角，叫什么角？",
    "锐角",
    "锐角比直角小；钝角比直角大。",
    "想想锐角、直角、钝角的大小。",
    { options: ["锐角", "直角", "钝角"] },
  ),
  q(
    "angle-4",
    "angles",
    "把角的两条边画得更长，角的大小会改变吗？",
    "不会",
    "角的大小与两条边张开的大小有关，与边画得多长无关。",
    "角的大小看的是“张开”的程度。",
    { options: ["会", "不会"] },
  ),
  q(
    "obs-1",
    "observation",
    "看一本平放的书，要看清封面，应该从哪个方向观察？",
    "上面",
    "从上面观察，可以看清平放的书的封面。",
    "封面正朝着哪个方向？",
    { options: ["上面", "下面", "侧面"] },
  ),
  q(
    "obs-2",
    "observation",
    "一个球，从前面、后面和侧面看，它的轮廓一样吗？",
    "一样",
    "球从这些方向看，轮廓都是圆形。",
    "想一想皮球的样子。",
    { options: ["一样", "不一样"] },
  ),
  q(
    "obs-3",
    "observation",
    "从不同方向观察同一个茶杯，看到的样子一定相同吗？",
    "不一定",
    "茶杯有把手，从不同方向看，把手的位置或可见程度可能不同。",
    "注意茶杯的把手。",
    { options: ["一定相同", "不一定"] },
  ),
  q(
    "time-1",
    "time",
    "分针走 1 大格，经过多少分钟？",
    "5",
    "钟面每个大格有 5 个小格，分针走 1 大格是 5 分钟。",
    "从数字 12 到数字 1 有几个小格？",
    { unit: "分钟" },
  ),
  q(
    "time-2",
    "time",
    "钟面上现在是几时几分？",
    "3:30",
    "分针指向 6，表示 30 分；时针在 3 和 4 之间，所以是 3 时 30 分。",
    "先看短短的时针，再看长长的分针。",
    {
      options: ["3:00", "3:30", "6:15"],
      visual: { type: "clock", hour: 3, minute: 30 },
    },
  ),
  q(
    "time-3",
    "time",
    "小禾 9:10 开始看书，看了 20 分钟。结束时是几时几分？",
    "9:30",
    "10 分加 20 分是 30 分，所以结束时是 9:30。",
    "20 分钟之后，时针还在 9 和 10 之间。",
    { options: ["9:20", "9:30", "10:10"] },
  ),
  q(
    "reason-1",
    "reasoning",
    "有 2 件上衣、3 条裤子。每次穿 1 件上衣和 1 条裤子，共有几种搭配？",
    "6",
    "每件上衣可以搭配 3 条裤子，2 件上衣共有 2 × 3 = 6 种搭配。",
    "先固定一件上衣，再换裤子。",
    { unit: "种" },
  ),
  q(
    "reason-2",
    "reasoning",
    "用 2、5 两张数字卡片组成两位数，每张只用一次，能组成几个不同的数？",
    "2",
    "可以组成 25 和 52，一共 2 个。",
    "分别让 2 和 5 站在十位上。",
    { unit: "个" },
  ),
  q(
    "reason-3",
    "reasoning",
    "小禾、小林、小雨，每两个人握一次手，一共握几次？",
    "3",
    "小禾和小林、小禾和小雨、小林和小雨，共 3 次。注意不要重复数。",
    "握过手的两个人不能重复算。",
    { unit: "次" },
  ),
];
export function publicQuestion(q: GradedQuestion): Question {
  return {
    id: q.id,
    topic: q.topic,
    prompt: q.prompt,
    hint: q.hint,
    ...(q.options ? { options: q.options } : {}),
    ...(q.unit ? { unit: q.unit } : {}),
    ...(q.visual ? { visual: q.visual } : {}),
  };
}
export function normalizeAnswer(value: string) {
  return value.normalize("NFKC").trim().replace(/\s+/g, "").replace(/：/g, ":");
}
export function gradeAnswer(question: GradedQuestion, answer: string) {
  const a = normalizeAnswer(answer),
    e = normalizeAnswer(question.answer);
  return /^\d+$/.test(e) && /^\d+$/.test(a) ? Number(a) === Number(e) : a === e;
}
